src/StreamJsonRpc.Desktop/project.json
src/StreamJsonRpc.NuGet/StreamJsonRpc.nuspec
src/StreamJsonRpc.Shared/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc.Shared/JsonRpc.cs
src/StreamJsonRpc.Shared/ReadBufferingStream.cs
src/StreamJsonRpc.Tests/PerfTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.ruleset
src/StreamJsonRpc/project.json

Note the target is the master branch. What we are shipping in Dev15 is in the v1.0 branch. So this PR is not subject to escrow.

Install Threading.Analyzers and get clean of messages

---

src/StreamJsonRpc/StreamJsonRpc.csproj

Turn off API checks for netstandard1.1 builds

---

CONTRIBUTING.md

Updated the file with new instructions due to the migration to the NET sdk

Updated contributing file with new build instructions

---

CONTRIBUTING.md

This causes issues if not installed when building.

Added Multilingual Toolkit step

---

src/StreamJsonRpc/EventArgs/DisconnectedReason.cs
src/StreamJsonRpc/EventArgs/JsonRpcDisconnectedEventArgs.cs
src/StreamJsonRpc/Exceptions/BadRpcHeaderException.cs
src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs
src/StreamJsonRpc/Exceptions/RemoteMethodNotFoundException.cs
src/StreamJsonRpc/Exceptions/RemoteRpcException.cs
src/StreamJsonRpc/Exceptions/RemoteTargetNotSetException.cs
src/StreamJsonRpc/JsonRpc.cs

This fixes the build warnings that plague the repo.

Document public APIs

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.cs.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.de.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.es.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.fr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.it.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ja.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ko.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pl.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pt-BR.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ru.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.tr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hans.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hant.xlf
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx

Implement multiple target support for StreamJsonRpc

Implement multiple target support for StreamJsonRpc

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

Prevent RPC from invoking methods on System.Object

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/DataContracts/JsonRpcMessage.cs

Fix invoking RPC methods whose only parameter is a CancellationToken

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.cs.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.de.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.es.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.fr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.it.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ja.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ko.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pl.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pt-BR.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ru.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.tr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hans.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hant.xlf
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx

Also validate inputs a bit more.

Add more AddLocalRpcMethod tests

---

README.md
doc/index.md

Adding an initial page for docs and sample usage for trivial cases

Adding docs for StreamJsonRpc

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/DataContracts/JsonRpcErrorCode.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/StreamJsonRpc.csproj

Throw OperationCanceledException instead of RemoteInvocationException when server method is canceled

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/Reflection/TargetMethod.cs

Fix support for combined CancellationToken and parameter objects

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/TestBase.cs

Add test for two synchronous Server methods running concurrently

---

src/StreamJsonRpc/JsonRpc.cs

This should increase efficiency and throughput slightly.

Execute server method continuation synchronously

---

src/StreamJsonRpc/JsonRpc.cs

I'd made the change locally in response to @ikeras's comment on #105 but failed to commit and push it before completing that PR. So here's the 1-line fix.

Clear field instead of clearing the collection

---

.travis.yml
src/StreamJsonRpc.Tests/JsonRpcClientInteropTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Allow for omission of whitespace between serialized JSON tokens 

---

src/StreamJsonRpc.Tests/JsonRpcClientInteropTests.cs
src/StreamJsonRpc/DataContracts/JsonRpcError.cs

Accept error responses where error.data is a primitive

---

src/StreamJsonRpc.Tests/JsonRpcClientInteropTests.cs
src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Expose error.data value from error responses in RemoteInvocationException

---

.vsts-ci.yml

This brings it to parity in functionality with AppVeyor

Update .vsts-ci.yml definition 

---

src/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
src/StreamJsonRpc/JsonRpc.cs

Ignore static and non-public events on target objects

---

src/StreamJsonRpc.Tests/DirectMessageHandler.cs
src/StreamJsonRpc.Tests/HeaderDelimitedMessageHandlerTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/MessagePackFormatter.cs
src/StreamJsonRpc.Tests/MessagePackFormatterTests.cs
src/StreamJsonRpc.Tests/StreamMessageHandlerTests.cs
src/StreamJsonRpc.Tests/XunitTraceListener.cs
src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc/IJsonRpcMessageFormatter.cs
src/StreamJsonRpc/IJsonRpcMessageHandler.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/LengthHeaderMessageHandler.cs
src/StreamJsonRpc/MessageHandlerBase.cs
src/StreamJsonRpc/PipeMessageHandler.cs
src/StreamJsonRpc/Protocol/JsonRpcError.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs
src/StreamJsonRpc/Protocol/JsonRpcResult.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Reflection/TargetMethod.cs
src/StreamJsonRpc/StreamMessageHandler.cs
src/StreamJsonRpc/WebSocketMessageHandler.cs

Add JSON-RPC message and event tracing

---

doc/dynamicproxy.md
doc/sendrequest.md

Inspired by the requirement expressed in #183

Add doc around sync-blocking RPC requests

---

src/StreamJsonRpc/StreamJsonRpc.csproj

This mitigates a security vulnerability in the 4.5.0 version.

Use System.IO.Pipelines 4.5.1

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/TestBase.cs

This supports diagnostics in test failures

Add more verbose logging in tests

---

src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs

Set JsonSerializer defaults consistent with 1.x versions

---

doc/connecting.md

I've spend an hour to understand why connection closing unexpectedly right after start. Only source code analyzing helped me to find a way out. Let's make it easier for others.

A bit more info

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/JsonRpcProxyOptions.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Add support for named parameters in generated proxies

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Add JsonRpc.ctor(Stream) overload

---

doc/recvrequest.md
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpcTargetOptions.cs

Default to not allowing non-public method invocation

---

src/StreamJsonRpc/JsonRpc.cs

Following an error in transmission of a r, nequesto response can be expected from the server. Yet until a response comes back, we were storing state in memory. This clears it out when an error occurs.
We have tests that cover the added code -- but testing for this particular leak is hard, so I didn't add any tests.

Avoid memory leak when transmitting a message fails

---

src/version.json

Removes -beta from 2.0 version spec

Ship 2.0 as stable package

---

doc/connecting.md
doc/extensibility.md

Beef up docs default and non-default protocol settings

---

src/StreamJsonRpc/LengthHeaderMessageHandler.cs
src/StreamJsonRpc/StreamJsonRpc.csproj
src/version.json

Use safe length prefixing technique with IBufferWriter<T>

---

src/StreamJsonRpc.Tests/SpecialCaseTests.cs

Add test to verify that the connection drops when a response cannot be transmitted

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

`StartListening` sets a `readLinesTask` field to the result of a `Task.Run` call that kicks off the listener. But if the listener starts, receives its first request, invokes the local RPC method, which then calls `JsonRpc.InvokeAsync`, all before the original thread that called `StartListening` is able to execute the field assignment, `InvokeAsync` will throw because it thinks `StartListening` has not yet been called.
The fix I've chosen is to put a couple of extra locks in place to guarantee the field assignment is executed before the listening method actually receives its first message.
I've also removed the `startedListening` field which is redundant with a `readLinesTask!=null` check.
Fixes #269

Fix race condition in StartListening

---

src/Benchmarks/.gitignore
src/Benchmarks/Benchmarks.csproj
src/Benchmarks/InvokeBenchmarks.cs
src/Benchmarks/NotifyBenchmarks.cs
src/Benchmarks/Program.cs
src/Benchmarks/run.cmd
src/StreamJsonRpc.sln

This adds a project that can measure GC pressure, CPU utilization, and more for common use cases of StreamJsonRpc.

Add Benchmark project

---

azure-pipelines/build.yml

Also remove workaround that is no longer necessary.

Update DotNetCoreInstaller task version

---

src/StreamJsonRpc.Tests/SpecialCaseTests.cs
src/StreamJsonRpc/JsonRpc.cs

Fixes #296 which describes a hang in this scenario.

 Fix JsonRpc to close the connection when its TraceListener throws

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/ProxyGeneration.cs

This is *not* more efficient than traditional Task. It's worse. But it allows proxy generation to support interfaces with ValueTask returning methods which is useful because those interfaces MAY not always be remoted. If the interface is there to support remoting but may also work directly, then ValueTask can provide a significant improvement to GC pressure since arbitrary values can be returned without allocating a Task<T> object.
Closes #302

Add support for ValueTask and ValueTask<T> returning methods

---

doc/index.md
doc/oob_streams.md
src/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
src/StreamJsonRpc.Tests/FullDuplexStream.cs
src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc.Tests/TestBase.cs
src/StreamJsonRpc.sln
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/MessageHandlerBase.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Reflection/MessageFormatterDuplexPipeTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterProgressTracker.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/StreamJsonRpc.csproj
src/StreamJsonRpc/xlf/Resources.cs.xlf
src/StreamJsonRpc/xlf/Resources.de.xlf
src/StreamJsonRpc/xlf/Resources.es.xlf
src/StreamJsonRpc/xlf/Resources.fr.xlf
src/StreamJsonRpc/xlf/Resources.it.xlf
src/StreamJsonRpc/xlf/Resources.ja.xlf
src/StreamJsonRpc/xlf/Resources.ko.xlf
src/StreamJsonRpc/xlf/Resources.pl.xlf
src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
src/StreamJsonRpc/xlf/Resources.ru.xlf
src/StreamJsonRpc/xlf/Resources.tr.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf

Add support for marshaling an IDuplexPipe or Stream as a JSON-RPC argument

---

src/StreamJsonRpc.Tests/JsonRpcRemoteTargetTests.cs

This test had been failing randomly with a thrown OperationCanceledException. This makes sense because the token being canceled can be handled by JsonRpc itself on the client side before even being transmitted, which will result in an OCE being thrown.
With this change, we guarantee to not cancel the token until the target method has begun execution, ensuring that nothing will throw OCE unless it fails and times out.

Fix unstable CanCancelOnOriginTarget test

---

src/StreamJsonRpc/JsonRpc.cs

Fix hang when ObjectDisposedException or OCE is thrown but for an unexpected reason

---

src/StreamJsonRpc/JsonRpc.cs

On .NET Framework, CancellationToken becomes half-broken after its CancellationTokenSource is disposed. This doesn't happen on .NET Core, or .NET Framework if the .exe.config file contains this:
```xml
<configuration>
<runtime>
<AppContextSwitchOverrides value="Switch.System.Threading.ThrowExceptionIfDisposedCancellationTokenSource=false" />
</runtime>
</configuration>
```
But as we want to behave properly without that switch on .NET Framework, this change replaces use of a linked CTS with a lone CTS that is temporarily linked by hand such that we can dispose the link later. By doing this, we achieve the same behavior but without a memory leak and without breaking the CancellationToken's use later.

Keep CancellationToken given to RPC methods working on net472 after method completion

---

doc/oob_streams.md
src/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs

Document proper stream disposal pattern

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

We have two code paths for dealing with exceptions thrown from RPC server methods. One handles faulted tasks returned from server methods and the other handles exceptions thrown directly from them. Only the faulted task path handled cancellation by reporting a cancellation to the client. The direct exception handling just treated them all the same in reporting a failure to the client.
This change catches `OperationCanceledException` thrown directly from the server method and returns the right canceled message to the client.
Fixes #441

Report cancellation when sync RPC methods throw OperationCanceledException

---

doc/dynamicproxy.md
src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/ProxyGeneration.cs

Allow RPC interfaces to derive from IDisposable

---

src/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
src/StreamJsonRpc.Tests/JsonRpcEnumerableSettingsTests.cs
src/StreamJsonRpc/Exceptions/UnexpectedEmptyEnumerableResponseException.cs
src/StreamJsonRpc/JsonRpcEnumerableSettings.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs

This contains the content of #451 plus 
77e67d6 Add validation for `JsonRpcEnumerableSettings.Prefetch`

Merge v2.4 to master

---

src/StreamJsonRpc/StreamJsonRpc.csproj

Fixes #455
This update contains [these changes](https://github.com/AArnott/Nerdbank.Streams/releases/tag/v2.4.67).

Update Nerdbank.Streams to 2.4.67

---

src/StreamJsonRpc/StreamJsonRpc.csproj

This applies the fix to https://github.com/AArnott/Nerdbank.Streams/issues/182

Apply fix for IAsyncEnumerable<T> failure

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.vscode/extensions.json
tools/Install-DotNetSdk.ps1

The Dockerfile is derived from https://github.com/microsoft/vscode-dev-containers/blob/master/containers/dotnetcore-3.1/.devcontainer/Dockerfile
The changes to `Install-DotNetSdk.ps1` are a copy-paste from the latest in https://github.com/AArnott/Library.Template/blob/master/tools/Install-DotNetSdk.ps1

Add devcontainer.json

---

doc/security.md

Add security.md file to resolve [this](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1120136) compliance task.

Added security.md file

---

azure-pipelines/secure-development-tools.yml

Removed extra space in secure-development-tools.yml to fix build

Removed extra space in secure-development-tools.yml

---

doc/disposable.md
doc/exotic_types.md
doc/general_marshaled_objects.md
doc/general_marshaled_objects_2.md
src/StreamJsonRpc.Tests/DisposableAction.cs
src/StreamJsonRpc.Tests/DisposableProxyJsonTests.cs
src/StreamJsonRpc.Tests/DisposableProxyMessagePackTests.cs
src/StreamJsonRpc.Tests/DisposableProxyTests.cs
src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc.Tests/TestBase.cs
src/StreamJsonRpc/IRpcMarshaledContext{T}.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcProxyOptions.cs
src/StreamJsonRpc/JsonRpcTargetOptions.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Reflection/MessageFormatterRpcMarshaledContextTracker.cs
src/StreamJsonRpc/RpcMarshaledContext{T}.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

Add support for marshaling IDisposable objects over RPC

---

src/StreamJsonRpc/Utilities.cs

Instead of calling `string.ToCharArray()` which allocates a new `char[]` each time it is invoked, we rent a `char[]` that is at _least_ as long as the string, and copy the string's contents into it. After creating a new string with the modified characters, we return the rented array for recycling.
This cuts down on GC pressure that showed up in Roslyn's perf tests.
Fixes #576

Recycle `char[]` in ToCamelCase

---

src/StreamJsonRpc/OptProf.targets

Turn off partial ngen for Dev17
See also devdiv-1336808

Turn off partial ngen for Dev17

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20210901200858603 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20210901200858603 to main

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20210903161557433 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20210903161557433 to main

---

loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20210903183148399 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20210903183148399 to main

---

src/StreamJsonRpc/Protocol/IJsonRpcMessageWithId.cs
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt

Expose the `IJsonRpcMessageWithId` interface publicly

---

doc/recvrequest.md

Document more about method overloading

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20220127163359139 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20220127163359139 to main

---

test/StreamJsonRpc.Tests/JsonRpcTests.cs
test/StreamJsonRpc.Tests/Samples/HttpClientMessageHandler.cs

We don't target netcoreapp2.1 any more.

Remove dead #if regions

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20220321153216891 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20220321153216891 to main

---

loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20220320153447176 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20220320153447176 to main

---

version.json

Update main to 2.12

---

src/StreamJsonRpc/SkipClrVisibilityChecks.cs
test/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs

Fixes issues @BertanAygun found from #804

Rename test and remove dead code

---

Directory.Build.props
Directory.Packages.props
azure-pipelines/OptProf.yml
azure-pipelines/official.yml
nuget.config
src/StreamJsonRpc/StreamJsonRpc.csproj
test/Benchmarks/Benchmarks.csproj
test/Directory.Build.props
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj

Switch to centrally managed package versions

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20221005153325251 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20221005153325251 to main

---

loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20221006153317260 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20221006153317260 to main

---

src/StreamJsonRpc/JsonRpc.cs

Also only consider the exceptions to be normal if the conditions we expect are true. Otherwise treat it as a fatal exception.

Retain the exception that leads to exiting the read loop

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20230317153255015 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20230317153255015 to main

---

loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20230319153255529 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20230319153255529 to main

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20230504153319649 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20230504153319649 to main

---

doc/extensibility.md

tests moved from src/ to test/

Fix dead link in doc/extensibility.md

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20240319153626139 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20240319153626139 to main

---

azure-pipelines/Archive-SourceCode.ps1
azure-pipelines/OptProf.yml
azure-pipelines/archive-sourcecode.yml

- Add missing TeamName to source code archival pipeline
- Fix test runner crash
- Further shore up timing break in test
- Fix empty optimization inputs drops
- Better logging on source code archival failure

Merge latest Library.Template

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20240801154552837 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20240801154552837 to main

---

version.json

17.12 package version stabilization

17.12 package version stabilization

---

src/StreamJsonRpc/JsonRpc.cs

Avoid unobserved exception when read loop fails

---

src/StreamJsonRpc/JsonRpc.cs

Also skip construction of an error response to notifications that will never receive it.
Fixes #1081

Replace warning with verbose message in log regarding `$/progress` not matching any method

---

Directory.Packages.props

security: bumps STJ to 8.0.5 due to security advisories

---

doc/extensibility.md

Commit c5fea7cf7c36510ee0a18a95113cdd0c84a66962 moved the location of `HttpClientMessageHandler.cs`. This PR adjusts sources to changes.

Update `HttpClientMessageHandler.cs` reference

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250120163502586 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250120163502586 to main

---

loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250121163424500 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250121163424500 to main

---

Directory.Packages.props
doc/vs.md
src/StreamJsonRpc/StreamJsonRpc.csproj
test/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
version.json

Drop the vs-threading analyzers from our package

---

loc/lcl/CHS/StreamJsonRpc.dll.lcl
loc/lcl/CHT/StreamJsonRpc.dll.lcl
loc/lcl/DEU/StreamJsonRpc.dll.lcl
loc/lcl/ESN/StreamJsonRpc.dll.lcl
loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/JPN/StreamJsonRpc.dll.lcl
loc/lcl/KOR/StreamJsonRpc.dll.lcl
loc/lcl/PLK/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl
loc/lcl/RUS/StreamJsonRpc.dll.lcl
loc/lcl/TRK/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250617153157620 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250617153157620 to main

---

loc/lcl/CSY/StreamJsonRpc.dll.lcl
loc/lcl/FRA/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250618153213638 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250618153213638 to main

---

loc/lcl/ITA/StreamJsonRpc.dll.lcl
loc/lcl/PTB/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250809153156222 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250809153156222 to main

---

loc/lcl/CHS/StreamJsonRpc.Analyzers.CodeFixes.dll.lcl
loc/lcl/CHS/StreamJsonRpc.Analyzers.dll.lcl
loc/lcl/CHT/StreamJsonRpc.Analyzers.dll.lcl
loc/lcl/CSY/StreamJsonRpc.Analyzers.dll.lcl
loc/lcl/ESN/StreamJsonRpc.Analyzers.CodeFixes.dll.lcl
loc/lcl/ITA/StreamJsonRpc.Analyzers.CodeFixes.dll.lcl
loc/lcl/ITA/StreamJsonRpc.Analyzers.dll.lcl
loc/lcl/PLK/StreamJsonRpc.Analyzers.dll.lcl
loc/lcl/PTB/StreamJsonRpc.Analyzers.dll.lcl
loc/lcl/TRK/StreamJsonRpc.Analyzers.CodeFixes.dll.lcl
loc/lcl/TRK/StreamJsonRpc.Analyzers.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250924153805077 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20250924153805077 to main
