src/StreamJsonRpc.Shared/DelimitedMessageHandler.cs
src/StreamJsonRpc.Tests/DelimitedMessageHandlerTests.cs
src/StreamJsonRpc.Tests/TestBase.cs

When an object is disposed of and the request is canceled, prefer throwing `OperationCanceledException` as callers tend to expect that.

Throw OperationCanceledExceptions instead of ObjectDisposedExceptions

---

init.ps1
src/.nuget/packages.config
src/StreamJsonRpc.NuGet/StreamJsonRpc.NuGet.nuproj
src/StreamJsonRpc.NuGet/project.json

Per the doc updates to NuProj found here:
nuproj/nuproj@883121f
We don't need to run "nuget restore project.json" on the NuProj directory directly any more. Using a solution-level packages.config file solves it in a simpler way.
Yes, this does mean that each solution has a local copy of the NuProj package after restore completes, but that's not too bad. And at least for this repo, that means that "nuget restore" on the solution always just works. And that's valuable.

Simplify package restore, and use latest NuProj

---

src/StreamJsonRpc.Shared/JsonRpc.cs

Exception message contained message and stack in one string. Related to [bug 392869](https://devdiv.visualstudio.com/DevDiv/Connected%20Experience/_workitems?id=392869)

removed stack from exception message

---

src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj

This additional line causes VS to complain regarding a duplicate package reference.

Fix Microbuild.NonShipping Duplicate Reference 

---

src/StreamJsonRpc.Tests/App.config
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj

Inspired by @sharwell's Microsoft/vs-threading#104, this makes tests "just work" in Test Explorer with skip verification and environment variables.

Test Explorer "just works" and project file touch ups

---

src/StreamJsonRpc.Tests/JsonRpcClientInteropTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc/DataContracts/JsonRpcError.cs
src/StreamJsonRpc/DataContracts/JsonRpcMessage.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/StreamJsonRpc.csproj

Fixes #44 (although we haven't figured out why C# dynamic fails sometimes).
This removes the last use of `dynamic` from the library.

Remove use of C# dynamic to avoid bizarre crash

---

src/Directory.Build.props
src/StreamJsonRpc.Tests/JsonRpcClientInteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/DataContracts/JsonRpcErrorCode.cs
src/StreamJsonRpc/EventArgs/DisconnectedReason.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Shipped.txt

Note this includes changes to PublicAPI.Shipped.txt but the renaming a generic type parameter is *not* a breaking change.

Update StyleCop package and fix up new warnings

---

src/StreamJsonRpc.Tests/FullDuplexStream.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs

HeaderDelimitedMessageHandler accepts cancellation token from the call
to JsonRpc.InvokeAsync. If the caller cancels the token at the right
moment, it may happen when the header is already written to the stream,
but the message content is not. If this happens, on the next call the
reciever will get a malformed message - a header from the first message,
a header and content from the next message. This will cause JsonRpc to
error out, close the stream, and cancel the next method.
This fix makes sure that writing in HeaderDelimiteMessageHandler occurs
atomically and cannot be interrupted by cancelled cancellation token.
Fix for #55.

Make HeaderDelimitedMessageHandler write atomic

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

Handle incoming request sequentially
To ensure that cancellation request is processed after the method it is cancelling, we handle all incoming requests sequentilly, and only yield when we execute user code.
Fixes #56

Fix race condition that can drop a cancellation request

---

src/StreamJsonRpc/Reflection/MethodSignature.cs

This fixes a perf regression since v1.3.6 because a local RPC target included public methods that were never invoked, but had a parameter whose type was defined in an assembly that did not need to load.

Avoid loading an assembly that defines parameter types unless necessary

---

.appveyor.yml
src/StreamJsonRpc.Tests/DirectMessageHandler.cs
src/StreamJsonRpc.Tests/PerfTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc/Exceptions/BadRpcHeaderException.cs
src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs
src/StreamJsonRpc/Exceptions/RemoteMethodNotFoundException.cs
src/StreamJsonRpc/Exceptions/RemoteRpcException.cs
src/StreamJsonRpc/Exceptions/RemoteTargetNotSetException.cs
src/StreamJsonRpc/ExcludeFromCodeCoverageAttribute.cs
src/StreamJsonRpc/StreamJsonRpc.csproj

This allows for exception serialization on .NET Standard 2.0 and prepares to use .NET Standard 1.3's support for TrySetCanceled

Add targets for net46, netstandard1.3, netstandard2.0

---

src/StreamJsonRpc.Tests/DelimitedMessageHandlerTests.cs
src/StreamJsonRpc.Tests/HeaderDelimitedMessageHandlerTests.cs
src/StreamJsonRpc.Tests/PerfTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc/DelimitedMessageHandler.cs
src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

This change adjusts the timing of flushing the stream and how quickly we exit the sending semaphore, allowing multiple message transmissions to line up right next to each other rather than being necessarily spaced apart for the entire time required to flush the previous message.
Fixes #52 
Probably also fixes #37 because we will hold the semaphore for a much smaller period of time.
This doesn't seem to significantly impact the "chatty" perf test we had before (or it makes it slightly slower). I added a new perf test for a burst of "notify" messages with these demonstrably improved results (*doubles* throughput):
```
BEFORE
Test Name:	PerfTests.BurstNotifyMessages(serverStream: FullDuplexStream { BeforeWrite = null, CanRead = True, CanSeek = False, CanTimeout = False, CanWrite = True, ... …
```

Improve performance of transmitting multiple messages

---

src/StreamJsonRpc.Tests/HeaderDelimitedMessageHandlerTests.cs
src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs

I noticed in writing some recent tests that if the `Subtype` property is changed on our delimited message writer, it would not emit the header anyway. This fixes that and adds the missing test.

Emit subtype header if it is nonstandard

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.cs.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.de.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.es.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.fr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.it.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ja.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ko.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pl.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pt-BR.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ru.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.tr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hans.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hant.xlf
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx

This adds a Task property that folks can await on when they want to proceed only after the client is done talking and has closed the pipe.
I rename and update the string resource for the exception we throw for operations that require listening to have started so that it is more generally applicable.

Add JsonRpc.Completion property

---

src/StreamJsonRpc/DelimitedMessageHandler.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

This further abstracts the use of Streams in `DelimitedMessageHandler` so that `WebSocket` can be used instead of Stream as the transport.

Add DelimitedMessageHandler.FlushCoreAsync() method

---

README.md
src/Directory.Build.props
src/Directory.Build.targets
src/StreamJsonRpc.Tests/TestBase.cs
src/StreamJsonRpc.Tests/WebSocketMessageHandlerTests.cs
src/StreamJsonRpc.sln
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/StreamJsonRpc.csproj
src/StreamJsonRpc/WebSocketMessageHandler.cs

Adds the `WebSocketMessageHandler` class to support the `WebSocket` class in .NET so this library can be used on a web server. `WebSocket` doesn't employ standard .NET `Stream` so it was necessary to add special support for it. This could have been done outside the library as well, but it seems like a reasonably common use case so this change makes it an included part of the library.
Note I take special care to handle messages that exceed the buffer size.
Tests included.

Add support for WebSocket

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Note that enabling this requires thread-safety in configuration modifications while receiving messages concurrently. This is already implemented before this change.
Closes #62

Allow JsonRpc modification while listening

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/AwaitExtensions.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

This allows the server methods to always be invoked on a particular thread for example, when using a single threaded `SynchronizationContext` such as the WPF `DispatcherSynchronizationContext`. 
It also provides a guarantee of method invocation order. The order the client transmits requests in becomes the order in which we call `SynchronizationContext.Post` for each method. After that, it's up to the `SynchronizationContext` to preserve order.
Closes #88

Support using SynchronizationContext to invoke server methods

---

src/StreamJsonRpc.Tests/DelimitedMessageHandlerTests.cs
src/StreamJsonRpc.Tests/WebSocketMessageHandlerTests.cs
src/StreamJsonRpc/DelimitedMessageHandler.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/WebSocketMessageHandler.cs

In applying the new `WebSocket` functionality of StreamJsonRpc to my project, I discovered that it throws `NullReferenceException` if the socket is closed, even if done so properly.
This fixes the `WebSocketMessageHandler` to handle the close scenario, and adds some defenses to its callers in case any other bad `DelimitedMessageHandler`-derived types similarly return empty strings.

Fix WebSocketMessageHandler's handling of closed sockets

---

.appveyor.yml
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc.Tests/WebSocketMessageHandlerTests.cs
src/StreamJsonRpc.sln
src/StreamJsonRpc/JsonRpc.cs

This adds a real ASP.NET Core (Kestral) web server based `WebSocket` that we test with.
While in there, I discovered a couple other minor things to fix up, including double-disposal of the `DelimitedMessageHandler` and solution items for build definitions.

Additional WebSocket tests and a double-disposal fix

---

.vsts-ci.yml

This brings VSTS up from its 4.1.0 default and should fix the package restore failure we're seeing.

Pin nuget.exe tool version to 4.6.2

---

doc/index.md
src/StreamJsonRpc.Tests/CommonMethodNameTransformsTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/CommonMethodNameTransforms.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/StreamJsonRpc.csproj

This allows for patterns already in use by the language server protocol and others where multiple target objects are added to the server side, with logical boundaries between these objects observable from the client by virtue of a 'namespace' being added to each method. Currently this is achievable by adding `JsonRpcMethodAttribute` to each method to change its name. This enhancement eliminates the need for manually transforming each individual method name.
It also gives the ability to do other interesting RPC method name transforms such as converting the typical PascalCase C# methods to be exposed with camelCase.
The method name transform is exposed as a `Func<string, string>` for maximum flexibility. But I add a `CommonMethodNameTransforms` static class with these two use cases …

Add support for RPC method name transforms when adding a local target objects

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

Previous to this change, a target object passed to StreamJsonRpc might look like this:
```cs
class Server
{
public void Foo() { }
[JsonRpcMethod("bar/soap")]
public void Whatever() { }
}
```
The `JsonRpcMethodAttribute` that appears changes the name of the method over RPC from `Whatever` to `bar/soap` (which isn't a legal CLR name). 
But as we look at proxy generation based on interface, we find that these special name-changing attributes need to be able to appear on interfaces as well so that the client proxy can generate code that invokes the method by the proper name (`bar/soap`, in this case). So with this change, you can now do this:
```cs
interface IServer
{
[JsonRpcMethod("bar/soap")]
void Whatever();
}
class Server : IServer
{
public void Foo() { }
public void Whatever() { }
}
``` …

Respect JsonRpcMethodAttribute appearing on interface methods

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs

This wasn't actually testing what it claimed to be, since it was sending the request to the same JsonRpc instance that was hosting the local objects. To actually test whether it will bind against a server object, the request must be sent from the *client* JsonRpc instance.

Fix test method AddLocalRpcTarget_NoTargetContainsRequestedMethod

---

src/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
src/StreamJsonRpc/JsonRpc.cs

This is a follow-up to #105 based on my conversations with @jasongin on that PR. It removes the static "null" argument from the notify messages that propagate a raised event from the local target object to the remote party.

Remove first (null) argument from notify events

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.cs.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.de.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.es.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.fr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.it.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ja.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ko.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pl.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pt-BR.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ru.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.tr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hans.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hant.xlf
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/StreamJsonRpc.csproj

When a JSON-RPC server offers a .NET interface that describes their API, StreamJsonRpc's `JsonRpc` class can now automatically generate a client proxy that implements that interface to give the client a strongly-typed way to send these RPC messages. This in effect replaces such code as:
```cs
var rpc = JsonRpc.Attach(stream);
Result result = await rpc.InvokeAsync<Result>("MyMethodAsync", 1, 2, "three");
```
with: 
```cs
IServer rpc = JsonRpc.Attach<IServer>(stream);
Result result = await server.MyMethodAsync(1,2, "three");
```
These client proxies also implement `IDisposable` if returned from the *static* `Attach<T>` method, since that is the only value that callers have that might be disposed to close the connection. There is also an instance method version of `Attach<T>`  so that more …

Add JsonRpc.Attach<T> client proxy generating method

---

src/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
src/StreamJsonRpc/JsonRpc.cs

Now that we allow JsonRpc users to transform every method name that is an RPC target, I noticed that accessor methods to events and properties (e.g. `add_SomeEvent` and `get_SomeProperty`) were also being selected as potential RPC target methods. This of course is not what the server target object is expecting, so this change filters those out.

Do not scan accessor methods on target objects

---

src/StreamJsonRpc.Tests/JsonRpcClientInteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcWithFatalExceptionsTests.cs
src/StreamJsonRpc.Tests/TestBase.cs

Catching OperationCanceledException is better than catch TaskCanceledException because OCE is the base class. CoreCLR seems to have a tendency to sporatically throw the base type instead of the derived type. And we don't really care which one is thrown, so stabilize the tests around it.
I also improve the test logging of GCPressure tests.

Fix tests that randomly fail on Travis CI

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

.NET Core 2.1 changed how async `Task<T>` returning methods run, such that they now return a derived-type of `Task<T>`. StreamJsonRpc used reflection to read `Task<T>.Result` and it wasn't prepared for a `Task<T>`-derived type. As a result, StreamJsonRpc is broken on .NET Core 2.1, in that any async method invoked by StreamJsonRpc will return `null` to the client as the result of the method instead of the actual value.
With this fix, we properly walk up the type hierarchy till we find the `Task<T>` so we can reliably find the `Result` property and call it. 
In the future, if this were to fail, we now fail hard (throwing an `InternalErrorException` instead of quietly returning null) to make this more discoverable.
In the process, I added .NET Core 2.1 as a target so tests always run on it, …

Fix handling of Task<T>-derived types returned from async methods

---

.appveyor.yml
.travis.yml
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj

Also take care to actually test our .netcoreapp1.0 library on .NET Core 1.x, instead of quietly running on 2.x because that's the only version of the runtime that is installed.

Add .NET Core 2.1 testing

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcProxyOptions.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Also create a new JsonRpcProxyOptions type and use that for dynamic client proxies. The JsonRpcTargetOptions type wasn't a good fit (it already has one extra property that is irrelevant to client proxies) and its name specifically refers to target objects, which the client proxy isn't one (conceptually anyway).
Fixes #119

Fix dynamic client proxies to honor method name transforms

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

Fixes #130 
The problem was we enter a loop when the server method returns a `Task` or `Task`-derived type. But the loop itself assumes that the loop (which walks up the type hierarchy) will always end up encountering a `Task<T>` type. Of course `Task` is the base type of `Task<T>` so if a `Task` is passed in, the loop will break (throwing an `ArgumentNullException`). The right behavior is to return null because the `Task` has no result value.

Fix handling of plain-Task returned objects from server methods

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcProxyOptions.cs
src/StreamJsonRpc/JsonRpcTargetOptions.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Adds usage of name transform functions to both proxy generation and also while raising notify messages. Adds unit tests for relevant cases. Fixes #135.

Ensures name transforms are used for events

---

src/StreamJsonRpc/DataContracts/JsonRpcMessage.cs
src/StreamJsonRpc/Reflection/MethodSignature.cs
src/StreamJsonRpc/Reflection/TargetMethod.cs

This is a bunch of micro-optimizations to remove allocations based on a study of PerfView memory allocation traces from work on https://github.com/AArnott/Nerdbank.Streams/issues/15.
This drops per-iteration allocations by about 50% (from 323 to 152 in my testing).

Reduce GC pressure

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc.Tests/WebSocketMessageHandlerTests.cs
src/StreamJsonRpc.sln
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/StreamJsonRpc.csproj
src/version.json

* Drop target frameworks: netstandard1.1, netstandard1.3, Profile259, and net45. This speeds up our builds and simplifies our code `#if` checks. We were never testing these two builds of the library so arguably we shouldn't have been shipping it. I add netstandard1.6 as a target (which we test) and covers [all the platforms](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) we care about anyway.
* Use master to track the 2.0-alpha version
I've pushed a v1.5 branch to track future 1.x work.

Introduce v2.0 and remove some target frameworks

---

src/Directory.Build.props
src/StreamJsonRpc.Tests/FullDuplexStream.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/JsonRpcWithFatalExceptionsTests.cs
src/StreamJsonRpc.Tests/MessageHeaderTests.cs
src/StreamJsonRpc.Tests/WebSocketMessageHandlerTests.cs
src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/StreamJsonRpc.csproj

These changes are a bunch of style or test resiliency changes. I made them as part of an upcoming change to add System.IO.Pipelines support to the API. That work is done, but this is a preliminary PR to get some of the noisier style/test changes out of the way first. The test changes fix issues where the tests were verifying behavior that was never reliable, and in fact changes later with the pipeline work.

Prepare for Pipelines

---

src/StreamJsonRpc/StreamJsonRpc.csproj

VS design-time components such as .resx to designer.cs file generation do so given the FIRST target framework. This must be set to a netstandard one so that the generated file will work on non-desktop builds as well.

Fix TargetFrameworks ordering

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Just a minor API addition. But without it, it may _appear_ that one cannot send a request with a parameter object that does not expect a result value.

Add non-generic InvokeWithParameterObject method

---

.vsts-ci.yml
src/version.json

This works around the build break that occurs on Azure Pipelines when a PR from a forked repo tries to set the build number.

Fix build break in PRs from forks

---

doc/index.md
doc/protocol.md
src/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
src/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/MessagePackFormatter.cs
src/StreamJsonRpc.Tests/MessagePackFormatterTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc/Protocol/JsonRpcError.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

To test this adequately I've split the JsonRpcTests class into two derived types to "replay" most tests against both MessagePack + Length handler as well as the original Json + Header handler stack.
At least for now, I'm leaving `MessagePackFormatter` in the test project rather than the library project. There are several optional paths folks can go down when using `MessagePack`, and any of them take about 1 line of code anyway. So rather than restrict folks to just one configuration, or writing code to support them all, the plan is to document the test project's version as a sample for folks to copy and/or inspire their own version.
Closes #124

Add MessagePack sample and tests

---

src/StreamJsonRpc/JsonRpc.cs

While working on #115, I happened across a fatal error in the traces that came from a race condition with disposal vs. cancelling a `CancellationTokenSource`. 
Connections that frequently cancel requests are at risk of dropping the entire connection as a result. This fixes the issue by swallowing the otherwise harmless exception.

Fix cancellation race that can result in connection termination

---

src/StreamJsonRpc.Tests/CommonErrorDataTests.cs
src/StreamJsonRpc.Tests/JsonRpcClientInteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
src/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/LocalRpcExceptionTests.cs
src/StreamJsonRpc/Exceptions/LocalRpcException.cs
src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Protocol/CommonErrorData.cs
src/StreamJsonRpc/Protocol/JsonRpcError.cs
src/StreamJsonRpc/PublicAPI.Shipped.txt
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Servers could already control the error.message property via the Message property on the exception they throw.
With this change, they can also control the error.code and error.data properties, by throwing a LocalRpcException which defines properties for these two other fields.
This also replaces the RemoteStackTrace and RemoteErrorCode properties which assumed a particular schema for the error.data object in favor of a new type that servers and clients can *optionally* use to convey this and more information.
The default behavior continues to include the information on the server we had before, plus the exception *type*.
Fixes #65

Enable JSON-RPC servers to completely control their error response

---

src/StreamJsonRpc.Tests/JsonRpcWithFatalExceptionsTests.cs
src/StreamJsonRpc/Exceptions/ConnectionLostException.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.cs.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.de.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.es.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.fr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.it.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ja.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ko.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pl.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pt-BR.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ru.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.tr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hans.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hant.xlf
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx

Specifically, fault the tasks with a ConnectionLostException for this scenario.
This is technically a breaking change, but it's one that Roslyn has requested, and we're making lots of breaking changes in 2.0, so it's a reasonable time to do it. The new exception derives from an existing base class for an exception so it should be easy for folks to catch properly if they're looking for the base class.
Fixes #84

Fault instead of cancel Tasks tracking outbound requests

---

src/StreamJsonRpc/DelimitedMessageHandler.cs

It turns out that some streams are not safe to flush and write to concurrently. The STDIN stream of a child process happened to be the stream that we were writing to at a very high frequency when data corruption occurred. I saw cases both where buffers were transmitted twice, and in other cases buffers were just skipped.
Fixes #174

Always flush within the write semaphore

---

src/StreamJsonRpc.Tests/JsonRpcWithFatalExceptionsTests.cs
src/StreamJsonRpc/JsonRpc.cs

The problem was we started shutting things down before faulting requests, such that a race existed in which requests might be "canceled" before we got around to faulting them. So with this change, we fault them *first*, then shut other stuff down.
This should stabilize the JsonRpcWithFatalExceptionsTests tests that are sporatically failing ever since 25a8e35ee was checked in.

More confidently fault aborted requests

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc.Tests/WebSocketMessageHandlerTests.cs
src/StreamJsonRpc/JsonRpc.cs

This worked on netcoreapp2.0 already, but when we started multi-targeting to netcoreapp2.1, the #if expressions were not updated, leading to a regression in functionality from 2.0 to 2.1.

Enable method rename behavior and tests on netcoreapp2.1

---

src/StreamJsonRpc/JsonRpc.cs

In response to https://github.com/Microsoft/python-language-server/pull/276#issuecomment-430812061 where we heard from the Python LSP owners that they want to send telemetry on exceptions.

Trace the exception details

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

There's no supported use case for overriding these.

Remove virtual modifier from InvokeCoreAsync methods

---

src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs

This fixes a regression from 1.x

Remove UTF-8 preamble from JSON-RPC messages

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

This worked in 1.x, but regressed in 2.x when we stopped using Newtonsoft.Json to obtain the property values.

Fix handling of params object with fields

---

src/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
src/StreamJsonRpc.Tests/MessagePackFormatter.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs

This fixes a regression from 1.x to 2.0, that originated when `JsonRpc` took upon itself the responsibility of dissecting a params object into its individual members. It did this without regard to the properties that Newtonsoft.Json would respect to change the names of the members, because at the `JsonRpc` level we don't know which formatter will be used.
The fix is simply to absolve `JsonRpc` of any responsibility to break up the params object, but rather just leave it as a params object in the `JsonRpcRequest`, leaving it to the formatter to represent. This alone made it work almost for free. Only minimal work in the `JsonMessageFormatter` was required for this to work.
The sample `MessagePackFormatter` included in the test project theoretically should support property renaming as well, …

Allow for message formatters to rename properties on param objects 

---

src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.cs.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.de.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.es.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.fr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.it.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ja.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ko.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pl.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pt-BR.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ru.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.tr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hans.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hant.xlf
src/StreamJsonRpc/Reflection/TargetMethod.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx

Before this change, when an argument is not supplied for a required parameter, the error the user would get was essentially "it didn't work for these reasons: " but no reason was given. The new string added in this PR adds the rest of this message so that a reason is actually given.

Improve error message when required arguments are missing

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/ProxyGeneration.cs

We weren't testing dynamic proxy generation with interfaces that derive from other interfaces. I stumbled across that while developing another feature and found it was broken. This fixes it, and adds a regression test.

Fix dynamic proxy generation from interfaces which implement other interfaces

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.cs.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.de.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.es.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.fr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.it.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ja.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ko.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pl.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pt-BR.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ru.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.tr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hans.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hant.xlf
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx

Enhances CancellationToken tests of the dynamic proxy generation, and fixes proxy gen to notice and report an error when the CancellationToken is not the last parameter. 
Before this change, the generated proxy would throw an `IndexOutOfRangeException` at runtime if the `CancellationToken` appeared as anything other than the last parameter of a method on the interface.

 Fix proxy gen detection of CancellationToken in unsupported position

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcTargetOptions.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Despite our intent and documentation that non-public methods should not be invokable using StreamJsonRpc, they are in fact invokable. Our unit test had a bug in it that was hiding this undesirable behavior.
Since fixing this to block non-public method invocation would be a breaking change at this point, rather than fix it immediately to block it, I add an option to block it so folks can opt into blocking non-public method calls. 
In a subsequent PR targeting our 2.0 release, I will change the default behavior to block non-public methods, forcing folks to opt *in* to allowing non-public method invocation, since that is what we told people we were doing already and from a security standpoint seems like the safer route.
Fixes #207

Add option to suppress non-public method invocation on server objects

---

doc/extensibility.md
src/StreamJsonRpc.Tests/Samples/HttpClientMessageHandler.cs
src/StreamJsonRpc/Exceptions/BadRpcHeaderException.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/StreamJsonRpc.csproj

JSON-RPC has a pseudo-spec for how to send JSON-RPC messages over HTTP. This PR adds an `IJsonRpcMessageHandler` that does just that, from the client side only. Because the spec is pretty sparse on detail, I haven't tested it and interop with other library implementations is worth testing before locking down behavior, I'm adding it merely as an extensibility sample.  Customers can copy it into their own project and tweak it to suit their needs, or given enough demand, we can promote it to part of the library with adequate testing.
Fixes #213

Add JSON-RPC over HTTP sample

---

src/StreamJsonRpc/JsonRpc.cs

While debugger inspecting private fields can often be useful, if they are just sync objects or redundant with properties, they are not useful.

Hide private fields from debugger browsing that are just noise

---

src/StreamJsonRpc.Tests/HeaderDelimitedMessageHandlerTests.cs
src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc.Tests/JsonRpcClient10InteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
src/StreamJsonRpc.Tests/MessageHeaderTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.cs.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.de.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.es.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.fr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.it.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ja.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ko.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pl.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.pt-BR.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.ru.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.tr.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hans.xlf
src/StreamJsonRpc/MultilingualResources/StreamJsonRpc.zh-Hant.xlf
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx

As part of this, I add a few validations when receiving JSON-RPC messages to verify they conform to the spec'd schema, at least in some ways. This extra validation helps to make sure folks are using the right protocol version setting in the `JsonMessageFormatter`. When turning this on, it caught a few tests that were not supplying the 2.0 protocol spec required `jsonrpc` property, so I fix those up too.
Fixes #220

Add support for JSON-RPC 1.0

---

src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs

StreamJsonRpc uses a two-step deserialization whereby we first read JTokens, then we later deserialize those JTokens with the user-provided `JsonSerializer`. It turns out that simply parsing the text into JTokens is a stage where some of the settings on the user-supplied `JsonSerializer` would have applied had it all been done in one step.
As this parsing step doesn't take a settings or a `JsonSerializer` object, the only thing we can do is manually copy the relevant settings from the user-supplied `JsonSerializer` object onto their matching properties on the `JsonTextReader`. 
Fixes #227

Apply JsonSerializer settings to JToken parser

---

src/Directory.Build.props
src/Directory.Build.targets

Fixes licenseUrl deprecation build warning.

Use new nuspec PackageLicenseExpression=MIT syntax

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs

Both return types and value types were failing when we check that a value is assignable to the required CLR type because we weren't expressly checking that a value type is a nullable one, and we assumed all value types cannot be `null`.
Fixes #237

Fix handling of nullable value types as RPC method parameters and return types

---

src/Directory.Build.props

This ensures we use SHA2 certs for all signing

Update MicroBuild package version

---

src/StreamJsonRpc/IJsonRpcMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Shipped.txt
src/StreamJsonRpc/PublicAPI.Unshipped.txt

These new overloads make it possible to create a dynamic client proxy that doesn't use the default HTTP+UTF8 handler/formatter.

Add more static JsonRpc.Attach<T> overloads

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Reflection/TargetMethod.cs

The C# compiler (or async method builder) emits code from an `async Task`-returning method that actually returns a `Task<VoidTaskResult>` instance. StreamJsonRpc was testing the returned value itself to see if it was a result-bearing `Task`, which this is, and was serializing the `VoidTaskResult` (an internal, empty struct) to the client. The client then saw a `{}` return value instead of `null`, as they would have seen from a plain `void` returning server method.
Besides the slight inaccuracy in the wire representation of the result, this caused an issue when using a serializer that doesn't know how to serialize the internal `VoidTaskResult` struct.
To fix this in a resilient way, I've opted for a slight behavioral breaking change in that if the server method is typed to return `Task` …

Do not return internal (empty) result from "async Task" methods

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/JsonRpcWithFatalExceptionsTests.cs
src/StreamJsonRpc/JsonRpc.cs

After canceling a request, frequently the client gets disposed. In 1.5 this would result in an expected cancelation state. In 2.0 this started throwing a ConnectionLostException if the dispose happened subsequently. Since the lost connection was a result of canceled request and not the cause of it, this adjusts the state of the task to match the expected state.
Tests were added to verify dispose does the expected behavior, as well as a lost connection still results in the ConnectionLostException.
Fixes: #265
@AArnott @tinaschrepfer

Throw OCE from canceled requests even when remote disconnects before sending cancellation acknowledgment

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs

Shows that #272 does not repro for v1.5

Add test that passes in a List<object> for arguments instead of object[]

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/MessagePackFormatter.cs
src/StreamJsonRpc.Tests/MessagePackFormatterTests.cs
src/StreamJsonRpc.Tests/Protocol/JsonRpcRequestTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

This corrects a regression in the 2.0 release where non-arrays could be passed in via the `IReadOnlyList<object>` parameter on `InvokeWithCancellationAsync`. We hadn't been testing with any non-array lists, and our API is actually inconsistent in support of these. So this fixes the regression by consistently using a new API to support it. But all existing JsonRpc consumers do not need to change. The new API is merely to support the formatters, which is an uncommon extensibility point.
Fixes #272

Allow non-array lists of arguments

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/JsonRpc.cs

Add support for proxy generated clients with event handlers that take args that do *not* derive from `EventArgs`.
**History lesson**: From .NET 2.0 to 4.0, the `EventHandler<T>` delegate type had a type constraint of `T : EventArgs`, meaning that the second parameter that the event handler takes must derive from `EventArgs. In .NET 4.5, this type constraint was *dropped*. Apparently they consider this a non-breaking change. But when dealing with code gen and reflection, all bets are off. :)
Not realizing this, my event wiring code assumed that deriving from `EventArgs` was a guarantee. As a result, when a user defines an event typed as `EventHandler<T>` where `T` does *not* derive from `EventArgs`, we would fail. 
This PR fixes it. Supporting `T : class` was as easy as changing …

Add support for TEventArgs without type constraints

---

src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessageHandlerBase.cs
src/StreamJsonRpc/StreamJsonRpc.csproj

This dramatically reduces GC pressure from `JsonMessageFormatter`.
1. Use shared array pool and recycle `Sequence<byte>` instance
1. Avoid allocating `Task<JsonRpcMessage>` for non-yielding server methods
1. Replace StreamWriter with BufferTextWriter
For each outgoing message, `JsonMessageFormatter` was creating a new `StreamWriter`, which allocated two large buffers. Since the `IBufferWriter<byte>` instance may vary across calls, we can't simply reuse a `StreamWriter` to avoid the allocations.
Instead we use a `TextWriter`-derived class which IS reusable across different target `IBufferWriter<byte>` instances. We allocate only one (char[]) buffer and encode directly to the memory returned from `IBufferWriter<byte>.GetMemory` so it's faster as well as much more GC friendly than the …

JsonMessageFormatter GC pressure fixes

---

src/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
src/StreamJsonRpc/JsonRpc.cs

Some servers do not strictly follow the JSON-RPC spec and stringify the
id, even if the client sent it as a number.
Note: We've already filed a bug against the service that stringifies all ids but we're not expecting a fix from them soon.
PS: I know you are not accepting pull requests yet but wanted to get this on your radar.

Be more liberal with the accepted type for a message id

---

src/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
src/StreamJsonRpc/JsonRpc.cs

The problem with #285 which introduced this bug is that it assumed that a generic event handler type would take one generic type parameter and that the generic type argument would be used as exactly the second parameter type in the event handler. 
The fix is to ignore whether the delegate is generic or not and simply look at the method signature of a delegate's `Invoke` method and match its second parameter type.
I defined a test on a commit based on `v2.0.187` (which did *not* have this bug) to verify the test passes. I then merged the tip of the `v2.0` branch and verified the test failed. The fix of course makes the test pass.
Fixes #292

Fix support for target object events with certain generic delegates

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/IJsonRpcClientProxy.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt

Fixes #298 by ensuring that *all* dynamic client proxies implement IDisposable.
Fixes #295 by implementing a new IJsonRpcClientProxy interface in each proxy that provides access to the JsonRpc object.

Provide all the same abilities in dynamic client proxies that JsonRpc itself has

---

src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc/IJsonRpcAsyncMessageFormatter.cs
src/StreamJsonRpc/IJsonRpcAsyncMessageTextFormatter.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/LengthHeaderMessageHandler.cs
src/StreamJsonRpc/PipeMessageHandler.cs
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/StreamJsonRpc.csproj

This replaces buffering large messages with async streaming deserialization where the formatter supports it.
The JsonMessageFormatter supports it with this change.
Fixes #310

Add async JSON deserialization support

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx

Fixed exception handling in TransmitAsync.

Fixed exception handling in TransmitAsync

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcEventSource.cs

A sample PerfView log:
Call stacks getting captured with the events:

Added ETW events

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/ProxyGeneration.cs

When a concrete type is passed to the proxy generator instead of an interface, we throw. But we have a bug in the construction of the exception message where if the concrete type is NOT a nested type, it throws NRE. This fixes that.

Fix NullReferenceException thrown in invalid proxy gen case

---

src/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
src/StreamJsonRpc/JsonRpc.cs

Tips for reviewers: 
* I changed the existing tests to use a derived type, which caused several to fail.
* I wrapped the existing event enumerating code to do so within an enumeration of the type hierarchy, using exactly the same technique we already used to find methods all the way up the hierarchy. All tests passed after that.
Fixes #340

Fix handling of events declared on the base types of target objects

---

src/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
src/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcCustomRequestIdTests.cs
src/StreamJsonRpc.Tests/JsonRpcRemoteTargetTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/MessagePackFormatter.cs
src/StreamJsonRpc.Tests/MessagePackFormatterTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc.Tests/StreamMessageHandlerTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Protocol/IJsonRpcMessageWithId.cs
src/StreamJsonRpc/Protocol/JsonRpcError.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs
src/StreamJsonRpc/Protocol/JsonRpcResult.cs
src/StreamJsonRpc/PublicAPI.Shipped.txt
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Reflection/MessageFormatterDuplexPipeTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterProgressTracker.cs
src/StreamJsonRpc/RequestId.cs
src/StreamJsonRpc/RequestIdJsonConverter.cs

This adds a virtual method to the JsonRpc class that allows advanced scenarios that require a specially customized request ID format. It creates a `RequestId` struct to encapsulate the string-or-integer that serves as the request ID and removes all assumptions from our code that our own locally generated request ID is an integer.
This makes some breaking public API changes, which I would typically avoid within a major release. Feel free to push back if you think this is a problem. I am thinking it's not as I've limited them to just the very new formatter-helper classes which are only used within custom formatter implementations of which there are few or none outside this repo at this point AFAIK.
Closes #329

Add support for custom (string based) request IDs

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PublicAPI.Shipped.txt
src/StreamJsonRpc/PublicAPI.Unshipped.txt
src/StreamJsonRpc/Reflection/JsonRpcMethodAttribute.cs
src/StreamJsonRpc/Reflection/MethodSignature.cs
src/StreamJsonRpc/Reflection/MethodSignatureAndTarget.cs

Support for deserializing params *object* as single first parameter

---

src/StreamJsonRpc/JsonRpc.cs

This change avoids an allocation if the `cancellationToken` passed in by the caller is the default `CancellationToken.None`.

Reduce allocations for invocations that have non-cancelable tokens

---

src/StreamJsonRpc/MessageHandlerBase.cs

We must not allow a race to exist between PipeReader/PipeWriter use and calling Complete() on them. This not only produces exceptions like the one in #350 but it opens up the possibility of accessing recycled buffers.
Fixes #350

Only complete PipeReader/PipeWriter after operations complete

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/MessageFormatterProgressTracker.cs
src/StreamJsonRpc/Reflection/TrackerHelpers.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Shipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Shipped.txt

* Fixes #371: Missing support for multiple `IProgress<T>` parameters on a single method
* Fix issues with IProgress<T> handling in the MessagePackFormatter, including around storing and reusing a buffer after it has been recycled by making a *copy* of the token we need to use later.
* Fixes MessagePackFormatter serialization of `IProgress<T>` instances when the concrete type is known statically due to being a member on a data contract class.
Also extract some general helper methods to another class so we can reuse it in IAsyncEnumerable<T> support.

Fix bugs in IProgress<T> handling

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/PipeMessageHandler.cs
src/StreamJsonRpc/Reflection/IJsonRpcMessageBufferManager.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

Move IJsonRpcMessageBufferManager into Reflection namespace

---

src/StreamJsonRpc/JsonMessageFormatter.cs

Fixes #377
The tests are added to the master branch in #382. They aren't added in v2.2 due to complicated merge conflicts.

Use user-supplied JsonConverters when deserializing IProgress<T> report

---

src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/IJsonRpcFormatterCallbacks.cs
src/StreamJsonRpc/Reflection/JsonRpcMessageEventArgs.cs
src/StreamJsonRpc/Reflection/JsonRpcResponseEventArgs.cs
src/StreamJsonRpc/Reflection/MessageFormatterDuplexPipeTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterProgressTracker.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Shipped.txt
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Shipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

Each tracker came with a burden on each formatter that used it that it had to be called at special times and in special ways. This change leverages some recently introduced interfaces so the trackers can take care of most needs themselves, simplifying the job of the formatters.
This includes breaking API changes to the trackers, but we've already made such changes in 2.3, and on the same basis that we aren't aware of any external users of it, it seems like a reasonable opportunity to simplify it.
The `IProgress<T>` tracker still has one special requirement because of when cleanup happens relative to the $/progress notifications, sadly. When we treat $/progress as just an ordinary method call it can be processed *after* the actual result from the method is received and its callback …

Replace specialized tracker code in formatters with general APIs

---

doc/asyncenumerable.md
src/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
src/StreamJsonRpc.Tests/JsonRpcExtensionsTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpcExtensions.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/xlf/Resources.cs.xlf
src/StreamJsonRpc/xlf/Resources.de.xlf
src/StreamJsonRpc/xlf/Resources.es.xlf
src/StreamJsonRpc/xlf/Resources.fr.xlf
src/StreamJsonRpc/xlf/Resources.it.xlf
src/StreamJsonRpc/xlf/Resources.ja.xlf
src/StreamJsonRpc/xlf/Resources.ko.xlf
src/StreamJsonRpc/xlf/Resources.pl.xlf
src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
src/StreamJsonRpc/xlf/Resources.ru.xlf
src/StreamJsonRpc/xlf/Resources.tr.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf

In particular:
* Remove any need to dispose of an enumerable's handle if it was fully enumerated or if any error occurred.
* Allow for including values in the initial message that discloses the handle.
Also use RFC 2119 key words in protocol spec.
Closes #384

Optimize RPC traffic for `IAsyncEnumerable<T>`

---

src/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
src/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs

Fix handling of exceptions thrown from result deserializers
I do this in two ways:
1. If any formatter throws an exception at this fragile point, kill the connection (as we were already doing) but also complete the one Task that we were abandoning before.
1. Fix the MessagePackFormatter to save its exception for a better time so the connection doesn't have to die.

Fix hang on deserialization exception

---

azure-pipelines/dotnet.yml
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc/Reflection/TargetMethod.cs
src/StreamJsonRpc/Utilities.cs

Add a workaround to a mono bug so StreamJsonRpc can run on mono (and support VS 4 Mac).
This also gets all our unit tests running on mono on Azure Pipelines except for the `PerfTests` class, which causes mono to crash.
Fixes #387

Workaround issues on mono and get tests running

---

azure-pipelines/OptProf.yml
azure-pipelines/dotnet.yml
src/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/PerfTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Reflection/CodeGenHelpers.cs
src/StreamJsonRpc/Reflection/TargetMethod.cs
src/StreamJsonRpc/StreamJsonRpc.csproj
src/StreamJsonRpc/Utilities.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

More than a merge... this required some fixes to run on mono, which v2.2 brought in and collided with other changes unique to master that broke mono further than v2.2 had fixed up for.

Merge v2.2 to master

---

src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/StreamJsonRpc.csproj

This requires we adapt to [some API changes](https://github.com/neuecc/MessagePack-CSharp/releases/tag/v2.0.299-rc) made in the RC.

Update MessagePack version

---

doc/exceptions.md
doc/recvrequest.md
doc/sendrequest.md
src/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
src/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs

Document (and test) that obtaining error data is much simpler now

---

src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

It isn't always possible to do, but when the server provides a `CommonErrorData` object, we certainly can do it.
I endeavored to copy the string format that .NET uses for its own exception formatting, including for inner exceptions.
Closes #369

Include RPC server stack trace in RemoteInvocationException.ToString()

---

src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc/IJsonRpcMessageFormatter.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/LengthHeaderMessageHandler.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/IJsonRpcFormatterTracingCallbacks.cs
src/StreamJsonRpc/Reflection/IJsonRpcTracingCallbacks.cs
src/StreamJsonRpc/Utilities.cs
src/StreamJsonRpc/WebSocketMessageHandler.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

We have JsonConverter and IMessagePackFormatter<T> types that have side effects in order to support marshaling of special objects. This makes tracing the full JSON-RPC message hazardous if it means we run these custom serializers multiple times per message, and this is in fact happening lately.
The fix is to be sure we only serialize/deserialize a message *once*. This means that the result of the serialization must be retained long enough to trace (if tracing is turned on). It also means we need to retain the text that was *de*serialized long enough to be traced. We also don't want to allocate a string for the entire message unless tracing requires it.
The approach varies between formatters, as follows:
For the `JsonMessageFormatter` we have a super-convenient `JToken` instance that …

Fix verbose RPC message tracing

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessageHandlerBase.cs

Fixes #396
**Important**: after completing this PR, the commits should be merged into master right away and completely neutralized. That is, run a merge that effectively excludes these commits changes. The changes are already in master and are leading to merge conflicts now with this change.

Avoid synchronous blocking in common case from JsonRpc.Dispose

---

doc/extensibility.md
src/StreamJsonRpc.Tests/NewLineDelimitedMessageHandlerTests.cs
src/StreamJsonRpc/NewLineDelimitedMessageHandler.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/xlf/Resources.cs.xlf
src/StreamJsonRpc/xlf/Resources.de.xlf
src/StreamJsonRpc/xlf/Resources.es.xlf
src/StreamJsonRpc/xlf/Resources.fr.xlf
src/StreamJsonRpc/xlf/Resources.it.xlf
src/StreamJsonRpc/xlf/Resources.ja.xlf
src/StreamJsonRpc/xlf/Resources.ko.xlf
src/StreamJsonRpc/xlf/Resources.pl.xlf
src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
src/StreamJsonRpc/xlf/Resources.ru.xlf
src/StreamJsonRpc/xlf/Resources.tr.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf

This new handler delimites JSON-RPC messages simply by a new line character.
I've heard of a few such JSON-RPC protocol implementations, which makes sense because people can simply type or paste a JSON-RPC message into a terminal and press enter and it will be processed.

Add NewLineDelimitedMessageHandler

---

src/StreamJsonRpc/PipeMessageHandler.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Shipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Shipped.txt

This is a follow-up to #350 which was evidently incompletely fixed. In the earlier fix, we arranged to Complete the reader and writer after they were done, which might be sometime after Dispose is called. This was all done in the base type. In the derived type, a Dispose override method Complete()'d the reader and writer anyway, defeating the very thing we were trying to fix. 
The fix is to remove these calls to Complete, leaving the base class to schedule these calls as it already does:
https://github.com/microsoft/vs-streamjsonrpc/blob/d7135f8e40898a0bce6a689a568aa9a65c0b13fc/src/StreamJsonRpc/MessageHandlerBase.cs#L64-L66
Fixes #413

Avoid completing reader or writer except after they are done

---

src/StreamJsonRpc/StreamJsonRpc.csproj

This addresses a leak (https://github.com/AArnott/Nerdbank.Streams/issues/162) where PipeStream doesn't get disposed when `PipeReader` and `PipeWriter` are completed.
To avoid package restore warnings, I had to bump another dependency as well.

Update Nerdbank.Streams to 2.4.57

---

doc/asyncenumerable.md
src/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcEnumerableSettings.cs
src/StreamJsonRpc/JsonRpcExtensions.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

This allows RPC server methods to return IAsyncEnumerable<T> with a prefetch setting without requiring them to call an async method and thus have to return a `Task<IAsyncEnumerable<T>>` instead of the more preferable `IAsyncEnumerable<T>` directly.
The trick here is that the `JsonRpc` class must itself perform the asynchronous `PrefetchAsync` operation after the RPC method returns but before sending the result for transmission to the formatter.
Closes #430

Add the JsonRpcEnumerableSettings.Prefetch property

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcTargetOptions.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

Add JsonRpcTargetOptions.DisposeOnDisconnect

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcTargetOptions.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

I added the the `UseSingleObjectParameterDeserialization` property to the target options. When the property is set to true, the `GetRequestMethodToClrMethodMap` method will add a `JsonRpcMethodAttribute` to the `MethodSignatureAndTarget`. I don't know if this is the correct approach because `GetJsonRpcMethodAttribute` will now return a attribute, that did not exist on the original method. But it seems like `AddLocalRpcMethod` is also creating fake attributes, so i think it should be ok.
resolves #444

Added UseSingleObjectParameterDeserialization option to JsonRpcTargetOptions

---

src/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
src/StreamJsonRpc.Tests/JsonRpcEnumerableSettingsTests.cs
src/StreamJsonRpc/Exceptions/UnexpectedEmptyEnumerableResponseException.cs
src/StreamJsonRpc/JsonRpcEnumerableSettings.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs

- 3653f3c Add test for throwing from the async iterator method
- 7dbc96a Avoid disposing of faulted RPC iterator
- 0a78bb9 Add `JsonRpcEnumerableSettings` range checks
- 31f332d Recognize and reject nonsensical responses from RPC servers
- 080aba4 Enable verbose tracing of `IAsyncEnumerable<T>`
Closes #445

Add test for async iterator method throwing an exception

---

src/StreamJsonRpc/PipeMessageHandler.cs

This prevents an exception being thrown (or worse: data corruption) as a connection is being torn down when the buffer is released by DisposeReader() followed by a later call to IJsonRpcMessageBufferManager.DeserializationComplete in the same class.

Clear reserved buffer on reader disposal

---

src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcRawStreamTests.cs
src/StreamJsonRpc.Tests/RequestIdTests.cs
src/StreamJsonRpc/EventArgs/DisconnectedReason.cs
src/StreamJsonRpc/EventArgs/JsonRpcDisconnectedEventArgs.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/RequestId.cs
src/StreamJsonRpc/RequestIdJsonConverter.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Shipped.txt
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Shipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/xlf/Resources.cs.xlf
src/StreamJsonRpc/xlf/Resources.de.xlf
src/StreamJsonRpc/xlf/Resources.es.xlf
src/StreamJsonRpc/xlf/Resources.fr.xlf
src/StreamJsonRpc/xlf/Resources.it.xlf
src/StreamJsonRpc/xlf/Resources.ja.xlf
src/StreamJsonRpc/xlf/Resources.ko.xlf
src/StreamJsonRpc/xlf/Resources.pl.xlf
src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
src/StreamJsonRpc/xlf/Resources.ru.xlf
src/StreamJsonRpc/xlf/Resources.tr.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf

JSON-RPC *allows* `null` as a request id value (bizarrely enough). And while we might not care to support interop with folks who use `null` as a value, it can legitimately come in response to a request where the server failed to parse in our request. I can't imagine a situation where that would happen, but there are pretty strange JSON-RPC servers out there, and I've heard from one user of this library that this came up.
The goal of this change is to update the code to acknowledge the validity of the `null` value at the schema level so that instead of a rather bizarre error when the situation is encountered, the oddity gets further in our pipeline where a more helpful error can be produced.
I add several tests including mocked up interop tests to demonstrate the intended behavior.

Fix deserialization of messages with null IDs

---

azure-pipelines/richnav.yml

This will make the repo available with rich nav at this prod endpoint: https://online.visualstudio.com/github/microsoft/vs-streamjsonrpc

point richnav to prod instead of int

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

This property returns a Task which completes whenever there are no local RPC methods currently running.
This allows shutdown code to not only wait for disconnection, but also for any trailing local RPC methods to finish running, if any.
Closes #466

Add JsonRpc.DispatchCompletion property

---

src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs

Fail gracefully if json-rpc 2.0 error or result is missing id

---

src/StreamJsonRpc.Tests/MessagePackFormatterTests.cs
src/StreamJsonRpc/MessagePackFormatter.cs

When the `MessagePackFormatter` decodes messages, it didn't skip values of unrecognized properties, leading to later failures that would express either as exceptions or dropped data.
This change adds tests and the fix to skip the unknown values.

Skip unrecognized properties in msgpack-encoded messages

---

doc/exotic_types.md
doc/extensibility.md
doc/index.md

While each exotic type had its own documentation, we didn't have a great place to send folks where a complete list was available. This fills that doc hole.

Document the exotic types

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

We didn't trace these before, and while `NotifyAsync` and other methods will propagate the exception to the caller, if the NotifyAsync call was made by a dynamically generated proxy in response to raising an event, the exception would be swallowed without a trace.
This also fixes invocation of the virtual `JsonRpc.OnRequestTransmissionAborted` method so that we only invoke it on actual transmission failures and not on all errors in receiving a response too.

Trace message transmission failures

---

azure-pipelines/microbuild.after.yml
azure-pipelines/secure-development-tools.yml

This would add Credscan and Policheck to the build to solve [this](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1120141) compliance task.

Added security tenet checking

---

src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc/JsonRpcEventSource.cs
src/StreamJsonRpc/LengthHeaderMessageHandler.cs
src/StreamJsonRpc/NewLineDelimitedMessageHandler.cs

Updated implementations of IJsonRpcMessageHandler to emit a new event including the size of payload. 
These implementations include those of: 
1. HeaderDelimitedMessageHandler.cs
2. LengthHeaderMessageHandler.cs

Add TransmissionCompletedSize ETW event

---

doc/oob_streams.md
src/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
src/StreamJsonRpc.Tests/JsonRpcRawStreamTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Reflection/MessageFormatterDuplexPipeTracker.cs
src/StreamJsonRpc/StreamJsonRpc.csproj

This PR enables the ability to return a stream as a server method to the client. 
The following corner cases have been added as tests:
- Support returning a stream from a server method
- Verify that a stream can be disposed after the client drops it
- Verify that custom return types with an inner stream also get a multiplexing channel
- Requesting a stream from a notification logs a warning and disposes of such stream immediately 
Closes #424

Support streams as a return type

---

src/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
src/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/MessageHandlerBase.cs

When a message is written to the output stream but not flushed, and then cancellation is requested, although the flush was canceled, the message was eventually going to be sent even though the client was no longer tracking it. This led to an unexpected response from the server to eventually be received and in v2.5, `JsonRpc` terminates the connection when the server sends an unexpected response to a request it doesn't remember sending.
The fix is to stop honoring the `CancellationToken` after the message has been written. We still honor the *disposal* token during flush so as to not hold up shutdown, but after a message is written, we always wait for flush to complete if we're still running.
Fixes #489

Fix mis-reported cancellation of message transmission

---

src/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
src/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
src/tests.ruleset

All of these were found by adding the vs-threading analyzers to the tests.
One of them was causing an unstable test that failed while an unrelated PR was being validated in Azure Pipelines.
We're seeing a lot of mono-mac crashes too, which are almost certainly attributing to the `async void` and associated test defect that this PR fixes.
Fixes #493

Fixes a few test issues

---

src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs

Newtonsoft.Json recognizes and reformats strings that look like dates by default. This is absolutely crazy, and has screwed up countless people, including our own users. Turn it off by default, and verify that folks can turn it back on if they really wanted it.
Fixes #487

Prevent JSON deserializer from scrambling dates

---

src/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs
src/StreamJsonRpc/Protocol/JsonRpcResult.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/xlf/Resources.cs.xlf
src/StreamJsonRpc/xlf/Resources.de.xlf
src/StreamJsonRpc/xlf/Resources.es.xlf
src/StreamJsonRpc/xlf/Resources.fr.xlf
src/StreamJsonRpc/xlf/Resources.it.xlf
src/StreamJsonRpc/xlf/Resources.ja.xlf
src/StreamJsonRpc/xlf/Resources.ko.xlf
src/StreamJsonRpc/xlf/Resources.pl.xlf
src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
src/StreamJsonRpc/xlf/Resources.ru.xlf
src/StreamJsonRpc/xlf/Resources.tr.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf

- Add several tests to demonstrate the expected use cases.
- Update the library to take declared argument types, and propagate these and return types to the formatter.
- Update the `MessagePackFormatter` to use this type info to serialize using the declared type so that union data wraps the msgpack data when appropriate.
- Optimize proxies to never allocate 0-length arrays.
MessagePack requires knowing the declared type as well as the object to actually serialize/deserialize. The declared type might be `BaseType` while the value itself might be an instance of `DerivedType`. When the declared type equals the value's actual runtime type, MessagePack simply serializes the value. But when the declared type is a base type of the value's type, MessagePack looks for a `[Union]` attribute on the …

Add support for MessagePack [Union] types as parameter and return types

---

src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs
src/StreamJsonRpc/JsonRpcEventSource.cs
src/StreamJsonRpc/LengthHeaderMessageHandler.cs

Previously we only reported on the size of messages *transmitted*. Now we report on the size of messages received as well.
I also give the events a different `Task` name to distinguish it from the `MessageTransmission` that is already used by `JsonRpc`.

Rename TransmissionCompletedSize event and add received event

---

azure-pipelines/secure-development-tools.yml

We were getting build warnings from Azure Pipelines about not using the latest version.
Also simplify the names used for both security tasks.
[sample run to show this works](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3899556&view=results).

Update CredScan version

---

src/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
src/StreamJsonRpc/Protocol/JsonRpcError.cs

The JSON-RPC spec allows for this property to be omitted.

Omit the error.data property when it is null

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/ExceptionSerializationHelpers.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

This adds support in both MessagePack and JSON formatters to serialize/deserialize `Exception`-derived types.
When a particular Exception type cannot be deserialized because it can't be loaded, we create an ordinary `System.Exception`.

Add support for serializing exceptions

---

src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/ProxyGeneration.cs

We should not use the short form jump instruction when the instructions between the jump source and target may exceed 127... (IL instructions? bytes?). Anyway, as a rule then, I've switched to long form whenever the jump crosses an IL generating loop, such that we can't be confident that the number of instructions will be small.
This regressed in 9cf9f7e86b089a19c6711eaba09e37e69e976669

Fixed proxy generation for methods with many parameters

---

src/StreamJsonRpc.Tests/MessagePackFormatterTests.cs
src/StreamJsonRpc/MessagePackFormatter.cs

This fixes #508, which describes how a recent change regressed one use case where custom formatters relied on a custom options class to carry information, but we replaced that options class with our own for the same purpose.
Since we can't both replace the options class without one stomping on the other, this change moves the private data that we need into a private *resolver* wrapper. We have always owned the outer-most resolver, so it's safe to do this as the external custom formatters couldn't be depending on anything at that level.

Preserve user-supplied MessagePackSerializerOptions

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

This provides the counterpart to the pre-existing virtual method `CreateErrorDetails`.
Closes #502

Expose CreateExceptionFromRpcError as a `protected virtual` method

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

This method restricts RPC surface area to only members defined on the type T instead of all (public) members on the target object.
Closes #517

Add JsonRpc.AddLocalRpcTarget<T> method

---

src/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
src/StreamJsonRpc/JsonRpc.cs

Before this fix, when events were declared (as abstract or virtual) on a base class and overridden in the target object, we attached a handler to the event once for each time it was declared in the hierarchy, leading to multiple invocations on the client.
Fixes #481

Only raise events from RPC targets once

---

doc/resiliency.md
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

Switch default to to retain order of incoming RPC invocations

---

doc/dynamicproxy.md
src/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
src/StreamJsonRpc/ProxyGeneration.cs

Dynamically generated RPC proxies implement void-returning methods by sending a notification instead of a request.
Closes #522

Add support for void returning methods in RPC interfaces

---

src/StreamJsonRpc.Tests/HeaderDelimitedMessageHandlerTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonRpc.cs

This PR adds tests to demonstrate which exception types are thrown in various disconnect scenarios.
It also improves documentation of these exceptions.
Closes #246

Document by test the exceptions thrown in disconnect scenarios

---

src/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
src/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
src/StreamJsonRpc.Tests/HeaderDelimitedMessageHandlerTests.cs
src/StreamJsonRpc.Tests/JsonRpcClient10InteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/xlf/Resources.cs.xlf
src/StreamJsonRpc/xlf/Resources.de.xlf
src/StreamJsonRpc/xlf/Resources.es.xlf
src/StreamJsonRpc/xlf/Resources.fr.xlf
src/StreamJsonRpc/xlf/Resources.it.xlf
src/StreamJsonRpc/xlf/Resources.ja.xlf
src/StreamJsonRpc/xlf/Resources.ko.xlf
src/StreamJsonRpc/xlf/Resources.pl.xlf
src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
src/StreamJsonRpc/xlf/Resources.ru.xlf
src/StreamJsonRpc/xlf/Resources.tr.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf

Wrap any/all exceptions thrown by formatters in the exception type native to their serializer.
This PR builds on #538, so until that completes, the diff on this PR will look larger than [its one unique commit](https://github.com/microsoft/vs-streamjsonrpc/pull/539/commits/de5cc5edd6b52a4faaf98b7cd15f46ab9bee06c6).

Tighten up exceptions thrown by formatters

---

src/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
src/StreamJsonRpc/Reflection/MessageFormatterProgressTracker.cs

Fix `IProgress<T>` when T is a MessagePack `[Union]` type

---

src/StreamJsonRpc.Tests/CustomCancellationStrategyTests.cs
src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/ICancellationStrategy.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Reflection/MethodSignatureAndTarget.cs
src/StreamJsonRpc/Reflection/TargetMethod.cs
src/StreamJsonRpc/StandardCancellationStrategy.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

This allows specific JsonRpc instances to be configured to implement `CancellationToken` support in a totally different way. They are *not* given the freedom to mutate the the request object itself, but they may trigger and respond to any other JSON-RPC message or do something entirely out of band (e.g. creating a file and/or testing for existing of the file).
As part of this change, we had to move `$/cancelRequest` handling out of its very special place in `JsonRpc.HandleRpcAsync` into a standard method handler. But that would have changed the method handler to be invoked on the user-configurable `SynchronizationContext` (which is now by default order-preserving). But this special method *shouldn't* be subject to that order-preserving `SynchronizationContext` because in fact we want …

Add ICancellationStrategy extensibility point

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs

These tests were vulnerable to the fact that `ProgressWithCompletion<T>` can invoke callbacks concurrently.

Fix unstable tests

---

src/StreamJsonRpc/JsonRpc.cs

Do not log transmission cancellation as an error

---

src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs
src/StreamJsonRpc/Exceptions/RemoteMethodNotFoundException.cs
src/StreamJsonRpc/Exceptions/RemoteRpcException.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Shipped.txt
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Shipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

Some of this error info was unique to `RemoteInvocationException` but some was replicated across `RemoteMethodNotFoundException` as well. In fact, most RPC error exceptions should include an error code, so promoting these to the base class makes sense.
But not *all* `RemoteRpcException` derived types come from a JSON-RPC error, so we must allow for not having an error code.
We also need to be creative to avoid any backward breaking API changes. So instead of *moving* the properties to the base class, I add them to the base class and 'redefine' them in the derived types to simply forward the value from the base class.

Promote error info into `RemoteRpcException`

---

src/StreamJsonRpc.Tests/JsonRpcTests.cs
src/StreamJsonRpc/Exceptions/RemoteSerializationException.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Protocol/JsonRpcErrorCode.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/xlf/Resources.cs.xlf
src/StreamJsonRpc/xlf/Resources.de.xlf
src/StreamJsonRpc/xlf/Resources.es.xlf
src/StreamJsonRpc/xlf/Resources.fr.xlf
src/StreamJsonRpc/xlf/Resources.it.xlf
src/StreamJsonRpc/xlf/Resources.ja.xlf
src/StreamJsonRpc/xlf/Resources.ko.xlf
src/StreamJsonRpc/xlf/Resources.pl.xlf
src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
src/StreamJsonRpc/xlf/Resources.ru.xlf
src/StreamJsonRpc/xlf/Resources.tr.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf

Previous to this change, a failure to serialize a response would lead the server to terminate the connection (since a response is required). With this change, we instead keep the connection going but send an error response to the client with the serialization error.
We also (still) log the serialization failure on the server.
Closes #549

Send error to client when server fails to serialize response

---

azure-pipelines/richnav.yml

A recent update to our service requires a Git token with all indexing requests. With this change, the Rich Nav task will have access to the aforementioned token to make requests to our service.

Begin using service connection for Git token

---

doc/exceptions.md
src/StreamJsonRpc/ExceptionProcessing.cs
src/StreamJsonRpc/Exceptions/RemoteInvocationException.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Protocol/JsonRpcErrorCode.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/.editorconfig
test/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
test/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

This was already possible in v2.6 thanks to #505, but it required overriding virtual methods to take advantage of. Now it's as easy as setting a property on the `JsonRpc` instance.
Closes #468

Add option to deserialize the original exception types thrown by the RPC server

---

src/StreamJsonRpc/JsonRpc.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

In particular I wanted to prove that `ObjectDisposedException` would not be thrown in the case of a dropped connection.
This raises confidence that folks really just need to be prepared for `RemoteRpcException` and derived types to be thrown so long as they don't have local coding bugs.

Improve ConnectionLostException docs and add a test

---

azure-pipelines/richnav.yml

We actually can't use the service connection with forks. Removing it as we no longer need it

Remove service connection that we actually can't use

---

src/StreamJsonRpc/CommonMethodNameTransforms.cs
src/StreamJsonRpc/Utilities.cs
test/StreamJsonRpc.Tests/AssemblyLoadTests.cs

The only dependency was our camelCase conversion.
This avoids an assembly load, which is independently valuable. But it is also a prereq to fixing #576.

Avoid loading Newtonsoft.Json in MessagePack scenarios

---

src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Protocol/JsonRpcError.cs

The MessagePackFormatter would deserialize error details twice. The first happened with a live buffer. The second one happened sometime later, concurrently with another thread that is clearing/recycling the buffer. This led to non-deterministic behavior including returning null as the error details but could also lead to reading corrupted data due to use of a recycled buffer.
Fixes #585

Fix possible data corruption from deserializing error details twice

---

src/StreamJsonRpc/MessagePackFormatter.cs

Several strings are *very* common in JSON-RPC. Rather than encode/decode them repeatedly, allocating new strings each time we decode, we instead use pre-encoded bytes and recognize the encoded bytes without decoding them.
The techniques used here come from MessagePack's own mpc-tool code output. So even though we're using MessagePack's "internal" namespace, it needs to be stable within a major version to keep mpc generated code working.
- [Sample deserialization decoder optimization](https://github.com/neuecc/MessagePack-CSharp/blob/896ed3c6bb3264bbda5c9a410a27d61b4cf1d93e/sandbox/Sandbox/Generated.cs#L1553-L1597)
- [Sample serialization encoder optimization](https://github.com/neuecc/MessagePack-CSharp/blob/896ed3c6bb3264bbda5c9a410a27d61b4cf1d93e/sandbox/Sandbox/Generated.cs#L1519-L1531) …

Reduce string encoding/decoding in MessagePackFormatter

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Reflection/MethodSignature.cs
src/StreamJsonRpc/Reflection/MethodSignatureAndTarget.cs
src/StreamJsonRpc/Reflection/RpcTargetInfo.cs

Cache the results of reflection based on the type and options so subsequent connections can be made faster and with less GC pressure.
Also move all the RPC target handling from JsonRpc to its own class.
This makes a short-lived "use once" JsonRpc connection 18% faster and cuts out some large allocations.
Related to #575

Optimize RPC target reflection

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterRpcMarshaledContextTracker.cs

These are a few simple improvements to reduce GC pressure and improve perf when setting up a JsonRpc connection, as guided by ETW traces.

Short-lived JsonRpc connection perf improvements

---

src/StreamJsonRpc/MessageHandlerBase.cs
src/StreamJsonRpc/MessagePackFormatter.cs

- Avoid boxing an enum in `MessageHandlerBase.SetState`
This was allocating 8012 objects in a perf trace I took (the no. 1 most allocated object). It should have been 0.
- Recycle ToStringHelper objects
This was the no. 2 allocated object in high traffic perf testing. Yet we only need one for serialization and one for deserialization. In this change, I create and cache these for reuse, bringing it down from 4000 in one test to just 4.

GC pressure fixes

---

src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Reflection/ExceptionSerializationHelpers.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/CollectingTraceListener.cs
test/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

There were a few issues:
1. We didn't gracefully handle exception types that were missing the `[Serializable]` attribute. Now we log a warning and just write out `CommonErrorData`.
1. We didn't gracefully handle exception types that were missing the deserializing constructor. Now we log a warning and deserialize the nearest base type that _does_ conform to the serializable pattern.
1. We weren't even serializing *thrown* exceptions to JSON ourselves (newtonsoft.json was doing it) which means it wasn't treated as 'user data'. Now we serialize thrown exceptions with our own converter as user data.
1. Exceptions weren't serialized to include their assembly name, so unless the assembly was already loaded, we wouldn't be able to activate it. Now we artificially add `AssemblyName` as a property …

Improve handling of various non-serializable Exception situations

---

src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/RpcTargetInfo.cs
test/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
test/StreamJsonRpc.Tests/TargetObjectEventsJsonTests.cs
test/StreamJsonRpc.Tests/TargetObjectEventsMessagePackTests.cs
test/StreamJsonRpc.Tests/TargetObjectEventsTests.cs

- Use default options as basis for MessagePack tests
- Get event wire-up tests running with MessagePack and get them passing
Previous to this the tests only ran on the JsonMessageFormatter. The tests failed on MessagePackFormatter because they were lacking a few formatters, one of which was customer impacting.
- Add type declaration when serializing TEventArgs type from server event.
This enables use of `Union` attributes when using the MessagePack formatter.
Fixes #612

Fix TEventArgs serialization from events when using MessagePack and union types

---

src/StreamJsonRpc/WebSocketMessageHandler.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
test/StreamJsonRpc.Tests/WebSocketMessageHandlerJsonTests.cs
test/StreamJsonRpc.Tests/WebSocketMessageHandlerMessagePackTests.cs
test/StreamJsonRpc.Tests/WebSocketMessageHandlerTests.cs

The problem was (and this is also explained in the original bug) the `WebSocketMessageHandler` was recycling its buffers after *partially* deserializing a message. This is fine for `JsonMessageFormatter`, which never has to read those same buffers again since it parsers the message into a `JToken` object graph. But for `MessagePackFormatter`, deserialization is altogether deferred for arguments/return values until we know what type to deserialize into, which means the buffer must not be recycled until the message is *fully* deserialized.
I added tests to identify the failure as well.
Fixes #548

Fix memory corruption in WebSocketMessageHandler when using MessagePackFormatter

---

azure-pipelines/variables/InsertConfigValues.ps1

This regressed in ab272a9d367400560bafaec77d62f9cd36ac4a51 when a 4th integer was added to the VSInsertionMetadata package.

Fix InsertConfigValues variable for 4-integer pkg versions

---

src/StreamJsonRpc/JsonMessageFormatter.cs

@davkean reports this costs us 20MB of memory.

Omit line info handling

---

Directory.Build.props
global.json
src/StreamJsonRpc/AwaitExtensions.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpcExtensions.cs
src/StreamJsonRpc/RequestIdJsonConverter.cs
src/StreamJsonRpc/StreamJsonRpc.csproj
test/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
test/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
test/StreamJsonRpc.Tests/JsonRpcClient10InteropTests.cs
test/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
test/StreamJsonRpc.Tests/JsonRpcCustomRequestIdTests.cs
test/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
test/StreamJsonRpc.Tests/NewLineDelimitedMessageHandlerTests.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
test/StreamJsonRpc.Tests/TargetObjectEventsJsonTests.cs

Also update other less noteworthy dependencies.

Update Newtonsoft.Json dependency to 13.0.1

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/JsonRpcEventSource.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs
src/StreamJsonRpc/netcoreapp2.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt

Presently, `JsonRpcEventSource.GetArgumentsString` prints dictionaries as ``System.Collections.Generic.Dictionary`2[System.String,System.Object]``, making `StreamJsonRpc/InboundCall` events unhelpful. Since `Dictionary<string, object>` seems like a case that would be generally useful when stringifying JSON objects, add special handling to `GetArgumentsString`.

Render named arguments in ETW events, including when using the MessagePack formatter

---

src/StreamJsonRpc/IJsonRpcMessageFactory.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Protocol/Constants.cs
src/StreamJsonRpc/Protocol/JsonRpcMessage.cs
src/StreamJsonRpc/Reflection/TargetMethod.cs
src/StreamJsonRpc/Resources.Designer.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/netcoreapp3.1/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/xlf/Resources.cs.xlf
src/StreamJsonRpc/xlf/Resources.de.xlf
src/StreamJsonRpc/xlf/Resources.es.xlf
src/StreamJsonRpc/xlf/Resources.fr.xlf
src/StreamJsonRpc/xlf/Resources.it.xlf
src/StreamJsonRpc/xlf/Resources.ja.xlf
src/StreamJsonRpc/xlf/Resources.ko.xlf
src/StreamJsonRpc/xlf/Resources.pl.xlf
src/StreamJsonRpc/xlf/Resources.pt-BR.xlf
src/StreamJsonRpc/xlf/Resources.ru.xlf
src/StreamJsonRpc/xlf/Resources.tr.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hans.xlf
src/StreamJsonRpc/xlf/Resources.zh-Hant.xlf
test/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs
test/StreamJsonRpc.Tests/JsonRpcDelegatedDispatchTests.cs
test/StreamJsonRpc.Tests/JsonRpcRemoteTargetTests.cs
test/StreamJsonRpc.Tests/JsonRpcWithMessageFactoryTests.cs
test/StreamJsonRpc.Tests/MessagePackFormatterTests.cs
test/StreamJsonRpc.Tests/Protocol/JsonRpcRequestTests.cs

Adds support for:
* Optional top level properties on RPC messages, and implementation of it for JSON and MessagePack formatters
* An option for JsonRpc implementations to handle dispatching of calls to target object to support scenarios like ordering calls, serializing calls without blocking JsonRpc stream.

Add support for top level properties and delegated dispatch

---

azure-pipelines/dotnet.yml
src/StreamJsonRpc/JsonRpcEventSource.cs

A regression was uncaught in v2.9 until inserted into VS where ETW tracing was on during perf tests. 
We'll avoid such a regression in the future by testing with ETW tracing code executing regularly going forward, starting with v2.8 before the regression.

Add ETW trace testing to pipeline

---

.editorconfig
StreamJsonRpc.sln
azure-pipelines/Windows_NT.runsettings

- Run tests on 64-bit process
- Update sln file

Run tests on 64-bit processes

---

test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj

Force upgrade of vulnerable System.Text.Encodings.Web 4.5.0 to 4.5.1.
This is according to https://github.com/dotnet/runtime/issues/49377

Force upgrade of vulnerable System.Text.Encodings.Web 4.5.0 to 4.5.1

---

src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpcTargetOptions.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/JsonRpcMethodAttribute.cs
src/StreamJsonRpc/Reflection/MessageFormatterProgressTracker.cs
src/StreamJsonRpc/Reflection/RpcTargetInfo.cs
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/JsonRpcServerInteropTests.cs
test/StreamJsonRpc.Tests/JsonRpcTargetOptionsTests.cs

An individual method or entire RPC target object may have this new option applied to get named arguments syntax used for callbacks (e.g. `IProgress<T>.Report` notifications).
This is useful for when the RPC client is LSP, which requires named arguments in the `$/progress` notification.
An LSP server that wishes to opt into this new behavior should add the RPC target option with an additional option:
```diff
rpc.AddLocalRpcTarget(
this.server,
new JsonRpcTargetOptions
{
UseSingleObjectParameterDeserialization = true,
+    ClientRequiresNamedArguments = true,
})
```

Add `ClientRequiresNamedArguments` option for `IProgress<T>` notifications

---

src/StreamJsonRpc/JsonMessageFormatter.cs
test/StreamJsonRpc.Tests/JsonMessageFormatterTests.cs

A recent change made in #651 regressed LSP when it changed from asking Newtonsoft.Json to serialize an entire custom params object to serializing each individual property. There are a bunch of considerations for each property that we were no longer taking into account (e.g. JsonConverter, default value skipping properties). 
Instead, we go back to letting JsonSerializer take care of the whole object, and simply delete the problematic property when the serializer includes it.
Fixes #735
@rruizGit You may be amused to learn I'm going back to your version of the fix, which gets the job done without breaking stuff as my version of the fix did.

Honor `[JsonConverter]` attributes on properties of custom params objects

---

src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/MessagePackFormatter.cs
test/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
test/StreamJsonRpc.Tests/JsonRpcServerInteropTests.cs

Discovered while attempting to use the new attributes added in https://github.com/microsoft/vs-streamjsonrpc/pull/733
Essentially when the client sends a request with a progress token using named parameters *and* the server is using `UseSingleObjectParameterDeserialization`, vs-streamjsonrpc fails to pass along the value of `clientRequiresNamedArguments` to the `JsonProgress` object.
This is exactly the configuration I hit as vscode uses named parameters and we make heavy use of `UseSingleObjectParameterDeserialization` in our lsp server.
The problem was that we essentially have a separate code path for handling RPC server methods that accept all args as a single argument (a special case built for LSP support), and we hadn't updated that code path to propagate the `JsonRpcMethodAttribute` …

Honor ClientRequiresNamedArguments when UseSingleObjectParameterDeserialization is set

---

src/StreamJsonRpc/ExceptionSettings.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/ExceptionSerializationHelpers.cs
src/StreamJsonRpc/StreamJsonRpc.csproj
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/ExceptionSettingsTests.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

- Suppress `WatsonBuckets` member from serialization
- Add recursion limit (so many inner exceptions get truncated at some point).
- Add the ability to filter exception types that can be deserialized.

Better handling of serializing exceptions

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/JsonRpcDelegatedDispatchAndSendTests.cs

Add a new SendAsync virtual method to JsonRpc to enable custom implementations to modify outgoing messages, such as adding top level properties.

Add SendAsync virtual method to JsonRpc

---

src/StreamJsonRpc/JsonRpc.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

The incoming RPC was getting an activity that bound only the time to invoke the server method and get its result back. But if the method were async, terminating the activity at that point meant the timestamp on the end of the activity would be premature. Instead, an async server method should mean the activity does not end until the returned Task completes. This makes it clear that child activities and other messages logged by the server method belong to that activity.
As shown in the Service Trace Viewer:
**Before**
**After**

Fix activity tracing to track entire execution time of inbound calls

---

src/StreamJsonRpc/JsonRpc.cs

See explanation in issue #772.

Handle FileNotFoundException thrown while deserializing exceptions

---

src/StreamJsonRpc/JsonMessageFormatter.cs
test/StreamJsonRpc.Tests/JsonContractResolverTests.cs
test/StreamJsonRpc.Tests/ObserverMarshalingTests.cs

Addressing failures similar to
```
StreamJsonRpc.RemoteMethodNotFoundException : Unable to find method 'xxx' on {no object} for the following reasons: Deserializing JSON-RPC argument with name "observer" and position 1 to type "xxx" failed: Could not create an instance of type xxx. Type is an interface or abstract class and cannot be instantiated. Path 'params[1].__jsonrpc_marshaled'.
```
when calling APIs under the following conditions:
- using Newtonsoft.Json
- the API has marshalable (`IObserver<>`, `IDisposable` or interfaces with `RpcMarshalableAttribute`) objects as parameters or return values
- the user replaces `JsonMessageFormatter`'s `ContractResolver`.
This issue has worsened since https://github.com/microsoft/vs-streamjsonrpc/pull/777 due to more behavior being delegated to …

Honor user-provided Json IContractResolver while maintaining marshaling capabilities

---

src/StreamJsonRpc/Reflection/RpcTargetInfo.cs
test/StreamJsonRpc.Tests/TargetObjectEventsTests.cs

Fix for issue #781. It includes a unit test that would have failed before the fix.

Hook events in base interfaces when calling `AddLocalRpcTarget<T>`

---

azure-pipelines/artifacts/VSInsertion.ps1

This fixes a regression from 8d6776369a0cf82c509f29e2001333ecb756d45b (the SBOM work) that broke optprof.

Build the VSInsertionMetadata package earlier in the pipeline

---

src/StreamJsonRpc/SkipClrVisibilityChecks.cs
test/StreamJsonRpc.Tests.ExternalAssembly/IInternalGenericInterface.cs
test/StreamJsonRpc.Tests.ExternalAssembly/InternalStruct.cs
test/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs

.NET Reflection doesn't report members as part of a derived interface. One must ask each interface up the type hierarchy for its members. In #789, an internal interface was defined in the local assembly and declared no members, so we thought no skip visibility attribute was necessary. Once we add the type hierarchy traversal, the additional assembly is discovered and the skip visibility attribute added, allowing the new test to pass.
Fixes #789

Fix visibility checks when generating proxies based on internal interfaces

---

test/Benchmarks/Benchmarks.csproj
test/StreamJsonRpc.Tests/CollectingTraceListener.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj

.NET 5 is no longer supported by Microsoft. Testing on a runtime that no one should be using is pointless, especially when we could test on a newer runtime that most folks are on.

Test on .NET 6 instead of .NET 5

---

azure-pipelines/variables/InsertTargetBranch.ps1
doc/vs.md
version.json

Note this builds on (and effectively reverts) the new commit added for the v2.13 branch, so that we continue to build and insert into the VS main branch.

Start building 2.14 versions

---

src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs

Calling `BufferBlock<T>.Complete()` can set its own `Completion` property to complete asynchronously. If `ReceiveAsync()` can throw due to completion *before* its `Completion.IsCompleted` is set to `true`, that would repro this problem. I haven't been able to confirm by code inspection or debugger that the `BufferBlock` could do this, but based on the exception you report, I can come to no other conclusion. Based on the documentation of the API, it appears that it's safe to assume than any `InvalidOperationException` is thrown only in the case of a completed block though, so to fix this, I will remove the `when` clause.
Fixes #867

Fix race condition in async enum tracker

---

src/StreamJsonRpc/ActivityTracingStrategy.cs
src/StreamJsonRpc/netstandard2.0/PublicAPI.Shipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Shipped.txt
test/StreamJsonRpc.Tests/ActivityTracingStrategyTests.cs

If there is no listener attached to the activity source, the activity will not be created, so fallback to create the Activity using the constructor

Allow users to pass in an ActivitySource to be used for generating a new Activity

---

Directory.Packages.props
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/JsonRpcTests.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj

This avoids deadlocks that RPC would otherwise introduce by carrying a `JoinableTask` token across RPC so that when/if the RPC call ever makes it back to the original AppDomain (or never leaves it) such that the callee needs the main thread, it will be able to reach it if the caller owns the main thread.

Add JoinableTaskFactory integration

---

doc/index.md
doc/joinableTaskFactory.md

#886 introduced JsonRpc-JoinableTaskFactory integration, but did not document it.

Document JTF integration

---

Directory.Packages.props
version.json

Version stabilization for 17. 6 release

Version stabilization for 17. 6 release

---

src/StreamJsonRpc/MessagePackFormatter.cs
test/StreamJsonRpc.Tests/MessagePackFormatterTests.cs

This feature is available in MessagePack but not on by default because it has a (small) perf cost when deserializing. But we want it on for RPC by default.
String interning means that we reuse string objects that are equal by value rather than creating new ones. We *don't* use `string.Intern` here because that keeps them in memory forever, and because that requires allocating a string before switching it for the long-lived instance. The way MessagePack (and this PR) does it requires no allocations at all if the string has been interned before. And the interning collection (which comes from MSBuild) is a weak intern, meaning string will not be held in memory for the life of the process.
I also use my `CommonString` type in a few more places. This has the effect of never deserializing even …

Intern strings when using the MessagePackFormatter

---

.editorconfig
doc/extensibility.md
src/StreamJsonRpc/Protocol/CommonErrorData.cs
src/StreamJsonRpc/Protocol/JsonRpcError.cs
src/StreamJsonRpc/Protocol/JsonRpcMessage.cs
src/StreamJsonRpc/Protocol/JsonRpcRequest.cs
src/StreamJsonRpc/Protocol/JsonRpcResult.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterRpcMarshaledContextTracker.cs
src/StreamJsonRpc/SystemTextJsonFormatter.cs
test/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs
test/StreamJsonRpc.Tests/SystemTextJsonFormatterTests.cs

It probably will meet more customer expectations (at least in the long term) if the default behavior of our System.Text.Json formatter matches the default behavior of the System.Text.Json serializer.
Also, @matteo-prosperi pointed out we do a lot of boxing in this implementation, which is something we should try to avoid in our official implementation.
Finally, it seems like if folks are looking for DCS compatibility, they may want to match behavior of unattributed types as well, but it turns out that in that mode, our class breaks on the simplest cases. This should probably also be fixed. But in the meantime, I've removed that option from what is now dead code.
We might bring it back, but it should be opt-in instead of opt-out, and it should ideally be more thoroughly tested and …

Remove DataContract attribute support from the STJ formatter

---

.config/dotnet-tools.json
.editorconfig
Directory.Packages.props
azure-pipelines/archive-sourcecode.yml
azure-pipelines/prepare-insertion-stages.yml
azure-pipelines/secure-development-tools.yml
azure-pipelines/variables/BinSkimTargets.ps1
azure-pipelines/vs-validation.yml
global.json
src/StreamJsonRpc/FormatterBase.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/SystemTextJsonFormatter.cs
tools/Install-DotNetSdk.ps1

- Fix ARM64 detection on Windows Powershell
- Bump up SDK and tools versions
- Skip symbol archival and checks for val-builds
- Copy the .config file when applying the template
- Upgrade `actions/checkout` GitHub action to v3
- Fix source archival pipeline nuget auth failures
- Fix and simplify BinSkim
- Elevate CA1062 for shipping code
- Bump Nerdbank.GitVersioning to 3.6.128
- Bump MicroBuild version
- Fix compilation warnings

Merge latest Library.Template

---

src/StreamJsonRpc/SystemTextJsonFormatter.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

The System.Text.Json serializer defaults to ignoring fields. For sake of meeting likely expectations, we should not mess with this default. Users can turn on this behavior easily enough if that's what they want. I had to update a few tests that depended on fields being serialized.
This is more along the lines of the spirit of #909, which similarly removed non-standard behavior from STJ.

Turn off field serialization in STJ by default

---

src/StreamJsonRpc/FormatterBase.cs
src/StreamJsonRpc/SystemTextJsonFormatter.cs
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt

Back in #908 during the refactoring that created a `FormatterBase` class, properties that used to be explicit interface implementations were made public. These properties are of no interest to the standard user of a formatter so I don't want them exposed publicly. They are still exposed via a public interface so that the advanced cases they were introduced to address are still addressed.
This is not a breaking change relative to our last stable release, because the APIs being removed were added only recently.

Remove properties inadvertently made public

---

src/StreamJsonRpc/HeaderDelimitedMessageHandler.cs

This string had \r\n in it, which just caused a newline to print, leading to a very confusing error message. I believe the intent was to print \r\n literally rather than a newline.
Discovered while working on [a pr for another project](https://github.com/ionide/LanguageServerProtocol/pull/51)

Fix unescaped newline in bad rpc header message

---

src/StreamJsonRpc/JsonMessageFormatter.cs
test/StreamJsonRpc.Tests/JsonRpcDelegatedDispatchAndSendTests.cs

Currently, `observedTransmittedRequestWithStringId` is not set when sending an instance of `OutboundJsonRpcRequest` because the condition checks for the wrong `JsonRpcRequest` class.

Fix string id detection for NormalizeId

---

src/StreamJsonRpc/NewLineDelimitedMessageHandler.cs
test/StreamJsonRpc.Tests/NewLineDelimitedMessageHandlerTests.cs

As requested in https://github.com/microsoft/vs-streamjsonrpc/discussions/959

Support `SystemTextJsonFormatter` in `NewLineDelimitedMessageHandler`

---

Directory.Packages.props
azure-pipelines/OptProf.yml
azure-pipelines/OptProf_part2.yml

VS Eng wants us to avoid using DD-CB-PR for non-PR builds, such as optprof runs.
I also had to revert a dependency upgrade to match what Dev17.4 ships to get the pipeline to run.

Fix optprof pipeline

---

doc/recvrequest.md

Was "NotifyClientsOfEvents" in docs, should be "NotifyClientOfEvents".

docs fix NotifyClientOfEvents option name

---

src/StreamJsonRpc/StreamJsonRpc.csproj

Microsoft.Bcl.AsyncInterfaces provides API that is already inbox on netstandard2.1. Don't reference the package for that framework to reduce the dependency graph.

Don't reference M.Bcl.AsyncInterfaces on netstandard2.1

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
test/StreamJsonRpc.Tests/JsonRpcJsonHeadersTypeHandlingTests.cs
test/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
test/StreamJsonRpc.Tests/JsonRpcSystemTextJsonHeadersTests.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

The bug description is found in #983.
The fix is simply to share the `JoinableTask` "token" across `JsonRpc` instances. We correlate `JoinableTask` tokens across `JsonRpc` instances (by default).
Mutable statics are more or less likely to cause problems with testing or advanced product scenarios. In this case though, it seems *very* likely that every shipping scenario will be drastically simpler by defaulting to sharing state across instances, so that is the default. Advanced cases can opt into isolating those instances however, and I have a test to verify this.    
Fixes #983

Fix deadlocks involving processes where JTF is _not_ present

---

azure-pipelines/CredScanSuppressions.json
azure-pipelines/official.yml

This gets our official pipelines running again.
The 'debug' mode we're putting credscan into isn't an acceptable long-term solution, but it allows us to exclude test log outputs from blocking the pipeline. I've reached out to the credscan team for a better solution.

Suppress credscan on test logs

---

src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
test/StreamJsonRpc.Tests/AsyncEnumerableTests.cs

In certain scenarios, there may have also been effectively a memory leak that this also fixes.
Fixes microsoft/vs-streamjsonrpc#999
This pull request primarily involves changes to the `src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs` file and the `test/StreamJsonRpc.Tests/AsyncEnumerableTests.cs` file. The changes aim to improve the tracking of outbound request IDs and their corresponding `IAsyncEnumerable<T>` state machines, and to update the test cases to reflect these changes.
Key changes include:
* The dictionary used to map outbound request IDs has been updated to track the list of tokens that represent `IAsyncEnumerable<T>` state machines it owns. This ensures that the state machines are cleaned up after receiving the final response.
* The …

Fixes early destruction of `IAsyncEnumerable<T>` sent as return value from RPC methods

---

doc/general_marshaled_objects.md

Adding some extra details to the marshaled object document about lifetimes.
I wrote this based on my understanding of a PR review comment from Andrew, so it might not be totally accurate.

Docs: add more detail about marshaled object lifetimes

---

test/StreamJsonRpc.Tests/MarshalableProxyTests.cs

Add test for marshalling one object twice

---

doc/rpc_marshalable_objects.md
src/StreamJsonRpc/DisposableAction.cs
src/StreamJsonRpc/FormatterBase.cs
src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterRpcMarshaledContextTracker.cs
src/StreamJsonRpc/Reflection/RpcMarshalableAttribute.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/SystemTextJsonFormatter.cs
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
test/StreamJsonRpc.Tests/MarshalableProxyTests.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
test/StreamJsonRpc.Tests/TestBase.cs

Add support for call-scoped marshalable objects

---

loc/lcl/DEU/StreamJsonRpc.dll.lcl

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20240320153615567 to main with localized lcls

LEGO: Pull request from juno/hb_152458e8-e8c0-49aa-b375-9938c873e7e8_20240320153615567 to main

---

test/StreamJsonRpc.Tests/JsonRpcClient20InteropTests.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs
test/StreamJsonRpc.Tests/MarshalableProxyTests.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
test/StreamJsonRpc.Tests/TestBase.cs

#1033 added a .NET 8 target to the library. With this change, we also explicitly run tests on it.
Because .NET 8 has removed the `BinaryFormatter`, the tests (which used it as a baseline for testing serializability of types) had to be updated to use a stand-in.

Test the .NET 8 build of the library

---

azure-pipelines/dotnet.yml
src/StreamJsonRpc/JsonRpcEventSource.cs
src/StreamJsonRpc/SharedUtilities.cs
src/StreamJsonRpc/SystemTextJsonFormatter.cs
test/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj

- Stop throwing from `TryGetArgumentByNameOrIndex` when using the `System.Text.Json` formatter
This also adjusts how we test with ETW events turned on so that issues like this will be caught rather than swallowed.
Fixes #1038
- Fix ETW logging of named arguments

Fix ETW logging of named arguments in System.Text.Json formatter

---

src/StreamJsonRpc/SystemTextJsonFormatter.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

Replacing the `Assumes.NotNull` with a non-throwing null check brings this formatter in line with the other formatters. 
The added unit test applies to _all_ formatters and demonstrated before the fix that only System.Text.Json failed the test. After the fix all formatters pass.
Fixes #1028

Fix System.Text.Json formatter's support for named arguments object

---

src/StreamJsonRpc/Reflection/TargetMethod.cs
src/StreamJsonRpc/net6.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/net8.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/JsonRpcDelegatedDispatchAndSendTests.cs

This allows logging based on overridding `DispatchRequestAsync` to know what the target method is.

Expose metadata about `TargetMethod` publicly

---

azure-pipelines/Get-SymbolFiles.ps1

This should keep it off the radar of the compliance check that we sign all shipping binaries.

Bucket benchmarks among test symbols

---

src/StreamJsonRpc/IJsonRpcClientProxyInternal.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Reflection/MessageFormatterRpcMarshaledContextTracker.cs
src/StreamJsonRpc/RpcMarshaledContext.cs
test/StreamJsonRpc.Tests/DisposableProxyTests.cs
test/StreamJsonRpc.Tests/MarshalableProxyTests.cs

Closes #1064
See that issue for details.

Enable sending RPC marshalable objects *back* to their owner

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Reflection/MessageFormatterRpcMarshaledContextTracker.cs
src/StreamJsonRpc/Resources.resx
src/StreamJsonRpc/net6.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/net8.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs

Previous to this, generated proxies allowed only one (primary) RPC contract interface.
They could also support "optional" interfaces to support `[RpcMarshalable]` scenarios, but this included a wire protocol difference (the optional interfaces would invoke methods with an integer prefix on each method name), and it wasn't exposed for direct use either.
Going forward for brokered services, we'd like to enable optional interfaces on them (https://github.com/microsoft/vs-servicehub/issues/225). The ideal way to expose this is for the brokered service *client* (that somehow knows which interfaces are supported by the service) to receive a proxy that implements all the right interfaces. 
*This* change will allow such a client to accomplish the proxy side of the work. The part about the client …

Enable generation of proxies that implement multiple interfaces

---

src/StreamJsonRpc/ProxyGeneration.cs
src/StreamJsonRpc/Resources.resx
test/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs

When multiple interfaces are expressly implemented, and one derives from another, it led to over-subscription of the events on the base interface, causing failures at runtime.
The fix is to ensure we only visit each member once, by visiting each *type* once, regardless of the number of times it is referenced directly or indirectly in the list of types to implement.
Now that we can handle interfaces being referenced twice *indirectly*, we might as well not throw when interfaces are referenced twice *directly*.
Use a diff view that doesn't call out whitespace changes, since some indentation-only changes have been made that clutters up the diff.

Fix proxies with derived interfaces

---

src/StreamJsonRpc/JsonRpc.cs
test/StreamJsonRpc.Tests/JsonRpcJsonHeadersTests.cs
test/StreamJsonRpc.Tests/JsonRpcMessagePackLengthTests.cs
test/StreamJsonRpc.Tests/JsonRpcSystemTextJsonHeadersTests.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs

Allow `JsonElement` as the `params` object in the `SystemTextJsonFormatter`

---

src/StreamJsonRpc/PipeMessageHandler.cs

Avoid crashing the process when `Stream.Dispose` throws

---

azure-pipelines/build.yml
azure-pipelines/official.yml

This avoids a build error when running credscan for the package publishing, since the suppression file is not available during that job.

Only use credscan suppressions for Windows build

---

src/StreamJsonRpc/Reflection/RpcTargetInfo.cs

This addresses https://github.com/microsoft/vs-streamjsonrpc/issues/1087

Fix disposal of marshalable object proxies

---

src/StreamJsonRpc/JsonRpc.cs

When a formatter throws an exception from `SetExpectedDataType`, the exception was being swallowed, and the request just dangled at the client without ever completing. With this fix, it completes with the exception. Since being unable to serialize a result is a fatal exception, this leads to the connection dying. This is preferable to a hang, and the exception is captured as the cause of the disconnect for later analysis.
There is no test because the existing formatters don't throw in this code path. A new formatter might (like the one we're creating for Nerdbank.MessagePack).

Fix connection hang upon failure to deserialize result values

---

src/StreamJsonRpc/JsonRpcEventSource.cs

Speedometer test shows two LOH allocations occurring in this method when opening a large cs file, when the value passed into JsonRpcEventSource.Format is a JsonDocument.
1) The ToString call on the document
2) The StringBuilder.Append call using the ToString result
It would be non-trivial to get rid of the first allocation, however, the second can be removed by just calling the StringBuilder.Append overload that takes in a range from the given string to copy into the StringBuilder.
Here's is the allocation from the speedometer test that this is attempting to improve:

Cap the amount of text copied into the stringbuilder in JsonRpcEventSource.Format

---

src/StreamJsonRpc/JsonRpc.cs

Since ProxyGeneration always generates IL code using RefEmit, it will never work in native AOT'd apps. But currently it is still brought into the app because RpcMarshalableConverterFactory (used by SystemTextJsonFormatter by default) eventually calls into it.
To remove references to Newtonsoft.Json, we can cut this off in AOT'd apps by checking if dynamic code isn't supported and throw an exception. This will allow ProxyGeneration to be trimmed from the final app.
This isn't a perfect fix, but instead a compromise. The best fix would be to make RpcMarshalableConverterFactory work correctly in AOT'd apps.
cc @AArnott

Cut ProxyGeneration out if dynamic code isn't supported

---

src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/Resources.resx

The call to JsonConvert from JsonRpc.InvokeCoreAsync is unconditionally preserving Newtonsoft.Json in trimmed/aot'd apps.
Inspecting the current code, I am not sure how this error case ever happens. The call to InvokeCoreAsync only returns JsonRpcError or JsonRpcResult objects. The else shouldn't ever be taken.
Instead of serializing the object using Newtonsoft.Json, simply put the object's Type into the exception message to indicate what the unexpected object was.
cc @AArnott

Remove Dependency on Newtonsoft.Json from JsonRpc

---

src/StreamJsonRpc/JsonMessageFormatter.cs
src/StreamJsonRpc/JsonRpc.cs
src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterProgressTracker.cs
src/StreamJsonRpc/Reflection/RpcTargetInfo.cs
src/StreamJsonRpc/Reflection/TrackerHelpers.cs
src/StreamJsonRpc/SystemTextJsonFormatter.cs
test/NativeAOTCompatibility/Program.cs

There are a couple patterns here:
- Use GetMemberWithSameMetadataDefinitionAs to reflect on generic types/methods in a statically verifiable fashion. This method only exists in .NET 6+.
- Suppress warnings when using GetInterfaces when the Type is annotated as preserve 'All'. https://github.com/dotnet/linker/issues/1731
- When looking for a hard-coded interface like IProgress<T>, any preserved Type that implements the interface won't have the interface trimmed.
- MethodNameMap uses GetInterfaceMap, which may not work in all cases. See https://github.com/dotnet/runtime/issues/89157
cc @AArnott 
FYI - @agocke @MichalStrehovsky - would you mind checking the suppressions I needed to add here? The biggest one is the GetInterfaceMap issue.

Refactor code and annotations to fix all warnings in NativeAOTCompatibility.

---

src/StreamJsonRpc/MessagePackFormatter.cs
src/StreamJsonRpc/Reflection/MessageFormatterEnumerableTracker.cs
src/StreamJsonRpc/Reflection/MessageFormatterProgressTracker.cs
src/StreamJsonRpc/Reflection/RpcMarshalableOptionalInterfaceAttribute.cs

- Remove leftover comment
- Fix some incorrect trimming annotations
cc @AArnott

Minor PR feedback

---

src/StreamJsonRpc.Analyzers/AttachAOTDiagnosticSuppressor.cs
src/StreamJsonRpc.Analyzers/ProxyGenerator.cs

In #1223 I added a source generator with an interceptor capability and a diagnostic suppressor. But the diagnostic suppressor ran unconditionally while the interceptor required opt-in, which would hide trim/dynamic code warnings inappropriately.
This fixes that.

Only suppress diagnostics when the interceptor is running

---

src/AnalyzerUser.targets
src/StreamJsonRpc/StreamJsonRpc.csproj
test/StreamJsonRpc.Analyzer.Tests/ProxyGeneratorTests.cs
test/StreamJsonRpc.Tests/ArchitectureTests.cs

This was causing runtime regressions in existing callers that were using the older APIs.
The interceptor was designed for _external_ assemblies. Not StreamJsonRpc itself.

Stop intercepting Attach calls within StreamJsonRpc itself

---

tools/Get-SymbolFiles.ps1

This fixes an official build break.
Cherry-pick of #1253

Classify UnreachableAssembly symbols as test symbol

---

Directory.Build.props
Directory.Build.targets
Directory.Traversal.targets
StreamJsonRpc.slnx
azure-pipelines/dotnet.yml
global.json
src/dirs.proj
test/AOT.props
test/NativeAOTCompatibility.Test/NativeAOTCompatibility.Test.csproj
test/dirs.proj
tools/dirs.proj

The NativeAOTCompatibility.Test project is published as part of our build pipeline as a test. Yes, the publish itself is the test, because in publishing, extra validation is performed by the .NET SDK to ensure that the code is NativeAOT-safe.
But in process of publishing it, we were also *re*-building its dependencies. Not only was this redundant, it was very slow on signed builds. Most importantly, it caused us to ship one set of binaries but archive symbols for an alternate set.
The problem was that we were building and packing first, then we were publishing which re-built but didn't re-pack. As a result, the nupkg packages were stale relative to the pdb's that were on disk from the later build. So we archived symbols based on the loose pdb files, but then we deploy the nupkg binaries. …

Eliminate over-build from the `dotnet publish` "test"

---

src/StreamJsonRpc/RpcTargetMetadata.cs

Loading the return type and parameters of a method forces the CLR to load the assemblies that declare those types. But unless the methods are invoked, we don't need to load them. This was showing up in a perf regression test.

Avoid loading assemblies unnecessarily

---

src/StreamJsonRpc/Reflection/RpcTargetInfo.cs
src/StreamJsonRpc/RpcTargetMetadata.cs
src/StreamJsonRpc/net8.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.0/PublicAPI.Unshipped.txt
src/StreamJsonRpc/netstandard2.1/PublicAPI.Unshipped.txt
test/StreamJsonRpc.Tests/JsonRpcProxyGenerationTests.cs
test/StreamJsonRpc.Tests/RpcTargetMetadataTests.cs

Dynamically generated proxies reliably invoke with non-aliased method names

---

test/StreamJsonRpc.Tests/AsyncEnumerableNerdbankMessagePackTests.cs
test/StreamJsonRpc.Tests/AsyncEnumerableTests.cs
test/StreamJsonRpc.Tests/DisposableProxyNerdbankMessagePackTests.cs
test/StreamJsonRpc.Tests/DisposableProxyTests.cs
test/StreamJsonRpc.Tests/DuplexPipeMarshalingNerdbankMessagePackTests.cs
test/StreamJsonRpc.Tests/DuplexPipeMarshalingTests.cs
test/StreamJsonRpc.Tests/JsonRpcNerdbankMessagePackLengthTests.cs
test/StreamJsonRpc.Tests/JsonRpcTests.cs
test/StreamJsonRpc.Tests/MarshalableProxyNerdbankMessagePackTests.cs
test/StreamJsonRpc.Tests/ObserverMarshalingNerdbankMessagePackTests.cs
test/StreamJsonRpc.Tests/RpcTargetMetadataTests.cs
test/StreamJsonRpc.Tests/StreamJsonRpc.Tests.csproj
test/StreamJsonRpc.Tests/TargetObjectEventsNerdbankMessagePackTests.cs
test/StreamJsonRpc.Tests/TargetObjectEventsTests.cs
test/StreamJsonRpc.Tests/WebSocketMessageHandlerNerdbankMessagePackTests.cs

We now can use method shapes (RPC contracts with `[GenerateShape(Methods)]` on them) to ensure that we have type shapes for all the RPC methods' parameter and return types.
We still need a `Witness` class in a few cases, including just a stub to reach the ShapeProvider to pass to the formatter.
Closes #1269

Replace tedious GenerateShapeFor attributes with method shapes

---

.github/renovate.json
Directory.Packages.props

We somehow ended up with 3 properties when we only needed and were using 2.

Fix msbuild analyzer version property

---

version.json

This PR neutralizes certain unwanted changes from the v2.23 branch. 
It also builds an unstable package because we have unstable dependencies, in order to fix the build break in our CI.

Merge v2.23 to main
